/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: D:/GitHub/mic-wagestat/layout/ESS/S54 集計用コード作成済データ.xls
    Date: 2021/03/12 16:37:32
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str var1 4-7
        str var2 8-9
        str KEN 12-13
        str var3 14-16
        str var4 18-20
        str var5 45-58
        str var6 61-62
        str var7 63-64
        str KTUZUKI 67-67
        str KSEI 68-68
        str var8 69-69
        str var9 70-71
        str var10 72-72
        str KNEN 73-75
        str KNEN5 76-77
        str KHAIGU 78-78
        str KSUMAI 80-80
        str KZKEN 81-82
        str KGAKU 91-91
        str KSYUGYO 94-94
        str YHTII 98-98
        str YKEIEI 100-100
        str YHNOU 101-101
        str YHSDAI 102-103
        str YHSANA 104-105
        str YHSANB 106-107
        str YH3BU 108-108
        str YHSHOKD 109-110
        str YHSHOKC 111-112
        str YKIBO13 115-116
        str YNISSU 118-118
        str YSKEITAI 119-119
        str YJIKAN 121-121
        str var11 122-123
        str YISIKI 138-138
        str YRIYU 139-139
        str YKKEITAI 140-140
        str YKATUDO 141-141
        str YFUKU 142-142
        str YFTII 143-143
        str YFNOU 144-144
        str YFSDAI 145-146
        str YFSAN 147-148
        str YFSYUNYU 149-149
        str YKEIZOKU 161-161
        str var12 163-164
        str YZSYUGYO 165-165
        str YSRIYU 166-166
        str MKIBOU 169-169
        str MRIYU 170-170
        str MSIGOTO 171-171
        str MKATATI 172-172
        str MKATUDO 173-173
        str MHOHO 174-174
        str MKIKAN 175-175
        str MJIKI 176-176
        str MZSYUGYO 177-177
        str ZRIYU 183-184
        str ZTII 186-186
        str ZNOU 187-187
        str ZSDAI 188-189
        str ZSAN 190-191
        str Z3BUMON 192-192
        str ZSHOKD 193-194
        str ZSYOKC 195-196
        str ZKIBO 197-198
        str SIPPAN 221-221
        str var13 226-226
        str var14 227-227
        str var15 228-228
        str var16 229-230
        str var17 231-232
        str SSYUNYU 245-246
    using "${path_data}/chosa/raw/210119　就業構造基本統計調査調査票情報データ/提供データ（統計委員会）/提供データ/L5_1979_RCD_AC2_A_S.TXT";
#delimit cr
