/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2021/03/12 16:37:32
-----------------------------------------------------------------------------*/


capture label variable var1 "ファイル定義: 西暦"
capture label variable var2 "ファイル定義: 調査月"
capture label variable KEN "地域: 県番"
capture label variable var3 "地域: 市区町村番号"
capture label variable var4 "地域: 調査区番号"
capture label variable var5 "ウェイト: 集計用乗率(14.9)"
capture label variable var6 "世帯番号"
capture label variable var7 "世帯員番号"
capture label variable KTUZUKI "基本属性続柄: 10区分"
capture label variable KSEI "基本属性: 性別"
capture label variable var8 "基本属性生年月: 年号"
capture label variable var9 "基本属性生年月: 年"
capture label variable var10 "基本属性生年月: 月"
capture label variable KNEN "基本属性年令: 各才"
capture label variable KNEN5 "基本属性年令: 5才階級"
capture label variable KHAIGU "基本属性: 配偶関係"
capture label variable KSUMAI "基本属性: 1年前の住居地"
capture label variable KZKEN "基本属性前住地: 県番"
capture label variable KGAKU "基本属性: 在学又は卒業学校"
capture label variable KSYUGYO "基本属性就業状況: 就業状況"
capture label variable YHTII "有業者本業について従業上の地位: 9区分"
capture label variable YKEIEI "有業者本業について: 経営組織"
capture label variable YHNOU "有業者本業について産業: 農非農"
capture label variable YHSDAI "有業者本業について産業: 大分類"
capture label variable YHSANA "有業者本業について産業: 中間分類"
capture label variable YHSANB "有業者本業について産業: 中分類"
capture label variable YH3BU "有業者本業について職業: 3部門"
capture label variable YHSHOKD "有業者本業について職業: 大分類"
capture label variable YHSHOKC "有業者本業について職業: 中間分類"
capture label variable YKIBO13 "有業者本業について従業員規模: 13区分(官公庁)"
capture label variable YNISSU "有業者本業について就業日数: 7区分"
capture label variable YSKEITAI "有業者本業について: 年間就業形態"
capture label variable YJIKAN "有業者本業について週間就業時間: 8区分"
capture label variable var11 "有業者本業について年間収入個人収入: 区分"
capture label variable YISIKI "有業者本業について就業希望: 意識"
capture label variable YRIYU "有業者本業について就業希望: 理由"
capture label variable YKKEITAI "有業者本業について就業希望: 形態"
capture label variable YKATUDO "有業者本業について: 求職活動の有無"
capture label variable YFUKU "有業者副業について: 副業の有無"
capture label variable YFTII "有業者副業について: 従業上の地位"
capture label variable YFNOU "有業者副業について産業: 農非農"
capture label variable YFSDAI "有業者副業について産業: 大分類"
capture label variable YFSAN "有業者副業について産業: 中分類"
capture label variable YFSYUNYU "有業者副業について年間収入個人収入: 区分"
capture label variable YKEIZOKU "有業者1年前について: 継続就業か否"
capture label variable var12 "有業者1年前について継続年数: 年数"
capture label variable YZSYUGYO "有業者1年前について: 就業状況"
capture label variable YSRIYU "有業者1年前について: 就業理由"
capture label variable MKIBOU "無業者就業希望: 有無"
capture label variable MRIYU "無業者就業希望: 理由"
capture label variable MSIGOTO "無業者就業希望: 仕事の主従"
capture label variable MKATATI "無業者就業希望: 形態"
capture label variable MKATUDO "無業者求職活動: 有無"
capture label variable MHOHO "無業者求職活動: 方法"
capture label variable MKIKAN "無業者求職活動: 期間"
capture label variable MJIKI "無業者: 就業希望時期"
capture label variable MZSYUGYO "無業者: 1年前の就業状況"
capture label variable ZRIYU "1年前の仕事について: 転・離職理由"
capture label variable ZTII "1年前の仕事について従業上の地位: 8区分"
capture label variable ZNOU "1年前の仕事について産業: 農非農"
capture label variable ZSDAI "1年前の仕事について産業: 大分類"
capture label variable ZSAN "1年前の仕事について産業: 中分類"
capture label variable Z3BUMON "1年前の仕事について職業: 3部門"
capture label variable ZSHOKD "1年前の仕事について職業: 大分類"
capture label variable ZSYOKC "1年前の仕事について職業: 中間分類"
capture label variable ZKIBO "1年前の仕事について: 従業員規模"
capture label variable SIPPAN "世帯について: 一般・単身"
capture label variable var13 "世帯について世帯人員: 0~5才"
capture label variable var14 "世帯について世帯人員: 6~11才"
capture label variable var15 "世帯について世帯人員: 12~14才"
capture label variable var16 "世帯について世帯人員: 14才以下"
capture label variable var17 "世帯について世帯人員: 15才以上"
capture label variable SSYUNYU "世帯について: 世帯収入区分"
