/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: D:/GitHub/mic-wagestat/layout/chingin/平成16_29年_賃金構造基本統計調査_符号表(個人票).xlsx
    Date: 2020/09/30 17:06:04
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str Chosa_Nen 1-4
        str Katsu 5-6
        str Ken 10-11
        str JigyoRen 12-16
        str Digit 17-17
        str Maime 18-19
        str RouRen 20-21
        str Shiku 22-24
        str Kihon 25-28
        str Jigyosyo 31-34
        str M_Sangyo 36-38
        str M_JigyoKibo 39-39
        str M_RinjiKibo 40-40
        str M_Kigyokibo 41-41
        str Sangyo 46-48
        str JigyoKibo 49-49
        str RinjiKibo 50-50
        str KigyoKibo 51-51
        str JigyoRitsu 52-55
        str RodoRitsu 56-57
        str RinjiRitsu 58-59
        str Fukugen 60-65
        str Honshi 66-66
        str Minko 67-67
        str Syurui 68-68
        str Syain_M 70-74
        str Syain_W 75-79
        str Hisyain_M 80-84
        str Hisyain_W 85-89
        str Rinji 90-94
        str SangyoDai 95-95
        str SangyoChu 96-97
        str SangyoSyo 98-98
        str Sei 104-104
        str Koyo 105-105
        str Syugyo 106-106
        str Gakureki 107-107
        str Nenrei 108-109
        str Kinzoku 110-111
        str RouSyu 112-112
        str Syoku 113-115
        str Keiken 116-116
        str RouNissu 117-118
        str SyoteiJikan 119-121
        str ChokaJikan 122-124
        str Genkin 125-129
        str ChokaKyuyo 130-133
        str SyoteiKyuyo 134-138
        str Tsukin 139-141
        str Seikin 142-144
        str Kazoku 145-147
        str Tokubetsu 148-153
    using "${path_chosa_raw}/200807　データ送付（厚生労働省）/調査票情報/賃金構造基本統計調査/h21_k-chin.txt";
#delimit cr
