/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: D:/GitHub/mic-wagestat/layout/maikin/h25_maikin_12_maikin_符号表.xls
    Date: 2020/08/11 21:22:29
-----------------------------------------------------------------------------*/


forvalues m = 1(1)12 {
	clear
	local m2f = strofreal(`m', "%02.0f")

	#delimit ;
		quietly infix
			str var1 1-1
			str var2 2-4
			str var3 5-7
			str var4 8-10
			str var5 11-12
			str var6 13-15
			str var7 16-19
			str var8 20-20
			str var9 21-23
			str var10 25-28
			str var11 29-32
			str var12 33-36
			str var13 37-40
			str var14 41-41
			str var15 42-42
			str var16 43-46
			str var17 47-48
			str var18 49-49
			str var19 50-50
			str var20 51-56
			str var21 57-62
			str var22 63-68
			str var23 69-74
			str var24 75-80
			str var25 81-88
			str var26 89-96
			str var27 97-104
			str var28 105-112
			str var29 113-122
			str var30 123-128
			str var31 129-134
			str var32 135-140
			str var33 141-146
			str var34 147-152
			str var35 153-160
			str var36 161-168
			str var37 169-176
			str var38 177-184
			str var39 185-194
			str var40 195-200
			str var41 201-206
			str var42 207-212
			str var43 213-218
			str var44 225-232
			str var45 233-240
			str var46 241-248
			str var47 249-256
			str var48 257-266
			str var49 267-274
			str var50 275-282
			str var51 283-292
			str var52 293-293
			str var53 294-294
			str var54 295-295
			str var55 296-296
			str var56 297-297
			str var57 298-298
		using "${path_chosa_raw}/200807　データ送付（厚生労働省）/調査票情報/毎月勤労統計調査/h25`m2f'_z-maikin.txt";
	#delimit cr

	tempfile m`m'
	qui save `m`m'', replace
}

clear
append using `m1' `m2' `m3' `m4' `m5' `m6' `m7' `m8' `m9' `m10' `m11' `m12'
