/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2020/08/11 21:22:29
-----------------------------------------------------------------------------*/


capture label variable var1 "M/C"
capture label variable var2 "識別符号"
capture label variable var3 "KEY1: 括番"
capture label variable var4 "KEY1: 通し番号"
capture label variable var5 "KEY: 府県"
capture label variable var6 "KEY: 調査区"
capture label variable var7 "KEY: 事業所一連・調査区内一連"
capture label variable var8 "KEY: 重複KEY"
capture label variable var9 "抽出符号"
capture label variable var10 "産業: 標準産業"
capture label variable var11 "産業集計産業コード: 大中分類"
capture label variable var12 "産業集計産業コード: 特掲産業1"
capture label variable var13 "産業集計産業コード: 特掲産業2"
capture label variable var14 "事業所規模"
capture label variable var15 "企業規模"
capture label variable var16 "調査年月: 年"
capture label variable var17 "調査年月: 月"
capture label variable var18 "事業所照合"
capture label variable var19 "内検ランク"
capture label variable var20 "区分1(男)常用労働者数: 前月末"
capture label variable var21 "区分1(男)常用労働者数: 増加"
capture label variable var22 "区分1(男)常用労働者数: 減少"
capture label variable var23 "区分1(男)常用労働者数: 本月末"
capture label variable var24 "区分1(男)常用労働者数: 本月末のうちパートタイム労働者"
capture label variable var25 "区分1(男): 出勤日数"
capture label variable var26 "区分1(男): 所定内労働時間"
capture label variable var27 "区分1(男): 所定外労働時間"
capture label variable var28 "区分1(男): きまって支給する現金給与額"
capture label variable var29 "区分1(男): 特別給与額"
capture label variable var30 "区分2(女)常用労働者数: 前月末"
capture label variable var31 "区分2(女)常用労働者数: 増加"
capture label variable var32 "区分2(女)常用労働者数: 減少"
capture label variable var33 "区分2(女)常用労働者数: 本月末"
capture label variable var34 "区分2(女)常用労働者数: 本月末のうちパートタイム労働者"
capture label variable var35 "区分2(女): 出勤日数"
capture label variable var36 "区分2(女): 所定内労働時間"
capture label variable var37 "区分2(女): 所定外労働時間"
capture label variable var38 "区分2(女): きまって支給する現金給与額"
capture label variable var39 "区分2(女): 特別給与額"
capture label variable var40 "区分3(パートタイム労働者)常用労働者数: 前月末"
capture label variable var41 "区分3(パートタイム労働者)常用労働者数: 増加"
capture label variable var42 "区分3(パートタイム労働者)常用労働者数: 減少"
capture label variable var43 "区分3(パートタイム労働者)常用労働者数: 本月末"
capture label variable var44 "区分3(パートタイム労働者): 出勤日数"
capture label variable var45 "区分3(パートタイム労働者): 所定内労働時間"
capture label variable var46 "区分3(パートタイム労働者): 所定外労働時間"
capture label variable var47 "区分3(パートタイム労働者): きまって支給する現金給与額"
capture label variable var48 "区分3(パートタイム労働者): 特別給与額"
capture label variable var49 "区分4(計): 超過労働時間給与"
capture label variable var50 "区分4(計): 超過労働時間給与(パートタイム労働者)"
capture label variable var51 "区分4(計): 特別給与額"
capture label variable var52 "変動理由: 定昇を実施した"
capture label variable var53 "変動理由: ベースアップを実施した"
capture label variable var54 "変動理由: 操業短縮、一時休業を実施した"
capture label variable var55 "変動理由: 休日に操業、営業等の事業活動を行った"
capture label variable var56 "変動理由: 制度上の週所定労働時間の短縮を実施した"
capture label variable var57 "変動理由: 夏休みなど、週休以外の休日を増やした"
