/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2020/08/11 21:22:29
-----------------------------------------------------------------------------*/


capture count if var1==.
if r(N)==_N {
    display as error "Only missing value: {bf:var1} (M/C)"
}


capture count if var2==.
if r(N)==_N {
    display as error "Only missing value: {bf:var2} (識別符号)"
}


capture count if var3==.
if r(N)==_N {
    display as error "Only missing value: {bf:var3} (括番)"
}


capture count if var4==.
if r(N)==_N {
    display as error "Only missing value: {bf:var4} (通し番号)"
}


capture count if var5==.
if r(N)==_N {
    display as error "Only missing value: {bf:var5} (府県)"
}
capture assert inlist(var5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, .)
if _rc!=0 {
    display as error "WARNING: {bf:var5} (府県) may have invalid values (Check layout sheet)"
}


capture count if var6==.
if r(N)==_N {
    display as error "Only missing value: {bf:var6} (調査区)"
}


capture count if var7==.
if r(N)==_N {
    display as error "Only missing value: {bf:var7} (事業所一連・調査区内一連)"
}


capture count if var8==.
if r(N)==_N {
    display as error "Only missing value: {bf:var8} (重複KEY)"
}
capture assert inlist(var8, 0, .)
if _rc!=0 {
    display as error "WARNING: {bf:var8} (重複KEY) may have invalid values (Check layout sheet)"
}


capture count if var9==.
if r(N)==_N {
    display as error "Only missing value: {bf:var9} (抽出符号)"
}


capture count if var10==.
if r(N)==_N {
    display as error "Only missing value: {bf:var10} (標準産業)"
}


capture count if var11==.
if r(N)==_N {
    display as error "Only missing value: {bf:var11} (大中分類)"
}


capture count if var12==.
if r(N)==_N {
    display as error "Only missing value: {bf:var12} (特掲産業1)"
}


capture count if var13==.
if r(N)==_N {
    display as error "Only missing value: {bf:var13} (特掲産業2)"
}


capture count if var14==.
if r(N)==_N {
    display as error "Only missing value: {bf:var14} (事業所規模)"
}
capture assert inlist(var14, 1, 3, 5, 7, 9, .)
if _rc!=0 {
    display as error "WARNING: {bf:var14} (事業所規模) may have invalid values (Check layout sheet)"
}


capture count if var15==.
if r(N)==_N {
    display as error "Only missing value: {bf:var15} (企業規模)"
}
capture assert inlist(var15, 1, 2, 3, 4, 5, .)
if _rc!=0 {
    display as error "WARNING: {bf:var15} (企業規模) may have invalid values (Check layout sheet)"
}


capture count if var16==.
if r(N)==_N {
    display as error "Only missing value: {bf:var16} (年)"
}


capture count if var17==.
if r(N)==_N {
    display as error "Only missing value: {bf:var17} (月)"
}


capture count if var18==.
if r(N)==_N {
    display as error "Only missing value: {bf:var18} (事業所照合)"
}
capture assert inlist(var18, 1, .)
if _rc!=0 {
    display as error "WARNING: {bf:var18} (事業所照合) may have invalid values (Check layout sheet)"
}


capture count if var19==.
if r(N)==_N {
    display as error "Only missing value: {bf:var19} (内検ランク)"
}


capture count if var20==.
if r(N)==_N {
    display as error "Only missing value: {bf:var20} (前月末)"
}


capture count if var21==.
if r(N)==_N {
    display as error "Only missing value: {bf:var21} (増加)"
}


capture count if var22==.
if r(N)==_N {
    display as error "Only missing value: {bf:var22} (減少)"
}


capture count if var23==.
if r(N)==_N {
    display as error "Only missing value: {bf:var23} (本月末)"
}


capture count if var24==.
if r(N)==_N {
    display as error "Only missing value: {bf:var24} (本月末のうちパートタイム労働者)"
}


capture count if var25==.
if r(N)==_N {
    display as error "Only missing value: {bf:var25} (出勤日数)"
}


capture count if var26==.
if r(N)==_N {
    display as error "Only missing value: {bf:var26} (所定内労働時間)"
}


capture count if var27==.
if r(N)==_N {
    display as error "Only missing value: {bf:var27} (所定外労働時間)"
}


capture count if var28==.
if r(N)==_N {
    display as error "Only missing value: {bf:var28} (きまって支給する現金給与額)"
}


capture count if var29==.
if r(N)==_N {
    display as error "Only missing value: {bf:var29} (特別給与額)"
}


capture count if var30==.
if r(N)==_N {
    display as error "Only missing value: {bf:var30} (前月末)"
}


capture count if var31==.
if r(N)==_N {
    display as error "Only missing value: {bf:var31} (増加)"
}


capture count if var32==.
if r(N)==_N {
    display as error "Only missing value: {bf:var32} (減少)"
}


capture count if var33==.
if r(N)==_N {
    display as error "Only missing value: {bf:var33} (本月末)"
}


capture count if var34==.
if r(N)==_N {
    display as error "Only missing value: {bf:var34} (本月末のうちパートタイム労働者)"
}


capture count if var35==.
if r(N)==_N {
    display as error "Only missing value: {bf:var35} (出勤日数)"
}


capture count if var36==.
if r(N)==_N {
    display as error "Only missing value: {bf:var36} (所定内労働時間)"
}


capture count if var37==.
if r(N)==_N {
    display as error "Only missing value: {bf:var37} (所定外労働時間)"
}


capture count if var38==.
if r(N)==_N {
    display as error "Only missing value: {bf:var38} (きまって支給する現金給与額)"
}


capture count if var39==.
if r(N)==_N {
    display as error "Only missing value: {bf:var39} (特別給与額)"
}


capture count if var40==.
if r(N)==_N {
    display as error "Only missing value: {bf:var40} (前月末)"
}


capture count if var41==.
if r(N)==_N {
    display as error "Only missing value: {bf:var41} (増加)"
}


capture count if var42==.
if r(N)==_N {
    display as error "Only missing value: {bf:var42} (減少)"
}


capture count if var43==.
if r(N)==_N {
    display as error "Only missing value: {bf:var43} (本月末)"
}


capture count if var44==.
if r(N)==_N {
    display as error "Only missing value: {bf:var44} (出勤日数)"
}


capture count if var45==.
if r(N)==_N {
    display as error "Only missing value: {bf:var45} (所定内労働時間)"
}


capture count if var46==.
if r(N)==_N {
    display as error "Only missing value: {bf:var46} (所定外労働時間)"
}


capture count if var47==.
if r(N)==_N {
    display as error "Only missing value: {bf:var47} (きまって支給する現金給与額)"
}


capture count if var48==.
if r(N)==_N {
    display as error "Only missing value: {bf:var48} (特別給与額)"
}


capture count if var49==.
if r(N)==_N {
    display as error "Only missing value: {bf:var49} (超過労働時間給与)"
}


capture count if var50==.
if r(N)==_N {
    display as error "Only missing value: {bf:var50} (超過労働時間給与(パートタイム労働者))"
}


capture count if var51==.
if r(N)==_N {
    display as error "Only missing value: {bf:var51} (特別給与額)"
}


capture count if var52==.
if r(N)==_N {
    display as error "Only missing value: {bf:var52} (定昇を実施した)"
}


capture count if var53==.
if r(N)==_N {
    display as error "Only missing value: {bf:var53} (ベースアップを実施した)"
}


capture count if var54==.
if r(N)==_N {
    display as error "Only missing value: {bf:var54} (操業短縮、一時休業を実施した)"
}


capture count if var55==.
if r(N)==_N {
    display as error "Only missing value: {bf:var55} (休日に操業、営業等の事業活動を行った)"
}


capture count if var56==.
if r(N)==_N {
    display as error "Only missing value: {bf:var56} (制度上の週所定労働時間の短縮を実施した)"
}


capture count if var57==.
if r(N)==_N {
    display as error "Only missing value: {bf:var57} (夏休みなど、週休以外の休日を増やした)"
}


