rename v1 KYOKUSYO
rename v2 SEIRI
rename v3 ITIREN_NO
rename v4 SEIBETU
rename v5 NENREI
rename v6 KINZOKU_NEN
rename v7 KYUYO_TUKI
rename v8 SYOKUMU
rename v9 KYUYO_TEATE
rename v10 SYOYO
rename v11 KYUYOGAKU_KEI
rename v12 NENZE_GAKU
rename v13 SYOTOKU_BAI
