/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: D:/GitHub/mic-wagestat/layout/ESS/S57 集計用個別データ.xls
    Date: 2021/03/12 16:37:32
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str CHO_YEAR 4-7
        str CHO_MONTH 8-9
        str CHIKI_KEN 10-11
        str CHIKI_CITY 12-14
        str CHIKI_CHONO 16-19
        str WAT_SHUKEI 58-68
        str S_RENBAN 70-71
        str S_ORGBANGO 72-73
        str S_SETIINNO 74-75
        str S_IPPAN 77-77
        str S_KAZOKURUI 85-85
        str S_JIN0 86-86
        str S_JIN1 87-87
        str S_JIN2 88-88
        str S_JIN3 89-89
        str S_JIN4 90-90
        str S_JIN5 91-91
        str S_JIN6 92-92
        str S_JIN7 93-93
        str S_JIN8 94-94
        str S_JIN9 95-95
        str S_JIN10 96-96
        str S_JIN11 97-97
        str S_JIN12 98-98
        str S_JIN13 99-99
        str S_JIN14 100-100
        str S_JIN15MI 101-102
        str S_JIN15IJO 103-104
        str S_OMOSYU 117-118
        str S_JYU1 119-119
        str S_JYU2 120-120
        str S_JYU3 121-121
        str S_JYU4 122-122
        str S_JYU5 123-123
        str S_JYU6 124-124
        str S_JYU7 125-125
        str S_JYU8 126-126
        str S_JYU9 127-127
        str S_JYU10 128-128
        str S_SHOTOKU 130-131
        str K_SEX 138-138
        str K_TUZUKI 140-140
        str K_NENGO 141-141
        str K_NEN 142-143
        str K_TUKI 144-144
        str K_AGE 145-147
        str K_AGE5 148-149
        str K_HAIGU 150-150
        str K_ZENJYU 151-151
        str K_ZENJYUKEN 152-153
        str K_SOTUGYO 157-157
        str K_GAKKO 158-158
        str K_SYUGYO 162-162
        str YH_JYUTII 169-169
        str YH_KOSHO 170-170
        str YH_KEIEI 171-171
        str YH_NOHINOU 172-172
        str YH_SAN3 173-173
        str YH_SANDAI 174-175
        str YH_SANM 176-177
        str YH_SANCHU 178-179
        str YH_SHODAI 180-181
        str YH_SHOM 182-183
        str YH_KAIKYU11 186-187
        str YH_NISSU 189-189
        str YH_JYUGYO 190-190
        str YH_JIKAN 192-192
        str YH_SHOTOKU 193-194
        str YH_SHUISIKI 197-197
        str YH_SYURIYU 198-198
        str YH_SYUKEITAI 199-199
        str YH_KATUDO 200-200
        str YF_FUKU 205-205
        str YF_JYUTII 206-206
        str YF_NOHINOU 207-207
        str YF_SAN3 208-208
        str YF_SANDAI 209-210
        str YF_SANCHU 211-212
        str YF_SHOTOKU 213-213
        str YZ_KEIZOKU 216-216
        str YZ_KEINEN10 217-218
        str YZ_KEINEN 219-220
        str YZ_SYUGYO 221-221
        str YZ_SYURIYU 222-222
        str YZ_ZENUMU 223-223
        str M_SYUKIBOU 226-226
        str M_SYURIYU 227-227
        str M_SYUSIGOTO 228-228
        str M_SYUKEITAI 229-229
        str M_KYUKATUDO 230-230
        str M_KYUHIRIYU 231-231
        str M_KYUHOHO 232-232
        str M_KYUKIKAN 233-233
        str M_KIBOJIKI 234-234
        str M_ZSYUGYO 235-235
        str M_ZENUMU 236-236
        str Z_RIJIKI2 240-240
        str Z_RIJIKINEN 241-242
        str Z_RIYU 250-251
        str Z_JYUTII 252-252
        str Z_NOHINOU 253-253
        str Z_SAN3 254-254
        str Z_SANDAI 255-256
        str Z_SANCHU 257-258
        str Z_SHODAI 259-260
        str Z_SHOM 261-262
        str Z_KAIKYU 263-264
        str Z_KEINEN 265-266
    using "${path_data}/chosa/raw/210119　就業構造基本統計調査調査票情報データ/提供データ（統計委員会）/提供データ/L5_1982_RCD_CB1_A_S.TXT";
#delimit cr
