/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2021/02/17 14:32:29
-----------------------------------------------------------------------------*/


capture label variable RES_NENTUKI "調査に関する事項: 調査実施年月"
capture label variable N_KEN "データ抜き出し情報調査区符号: 都道府県番号"
capture label variable N_KENNAI "データ抜き出し情報調査区符号: 都道府県内一連番号"
capture label variable N_SETAI1 "データ抜き出し情報世帯番号: 居住者の有無(世帯番号)"
capture label variable N_SETAI2 "データ抜き出し情報世帯番号: 抽出単位番号(世帯番号)"
capture label variable N_SETAI3 "データ抜き出し情報世帯番号: 世帯一連番号(世帯番号)"
capture label variable N_SETAIINNO "データ抜き出し情報: 世帯員番号"
capture label variable C_KEN "所在地に関する事項市区町村情報市区町村コード調査実施時: 都道府県(調査実施時)"
capture label variable C_CITY "所在地に関する事項市区町村情報市区町村コード調査実施時: 市区町村(調査実施時)"
capture label variable R_KEN "乗率: 都道府県番号"
capture label variable R_RITSUBLKNUM "乗率: 県内経済圏用"
capture label variable R_SHUKEI "乗率: 集計用乗率"
capture label variable KC_JININ "オリジナル情報(最終チェック済データ)調査員記入欄: 世帯人員(15歳以上)"
capture label variable KC_1_SEX "オリジナル情報(最終チェック済データ)個人事項: 1男女の別"
capture label variable KC_1_HAIGU "オリジナル情報(最終チェック済データ)個人事項: 1配偶関係"
capture label variable KC_2_TSUZUKI "オリジナル情報(最終チェック済データ)個人事項: 2続き柄"
capture label variable KC_3_GENGO "オリジナル情報(最終チェック済データ)個人事項: 3出生年月(元号)"
capture label variable KC_3_NEN "オリジナル情報(最終チェック済データ)個人事項: 3出生年月(年)"
capture label variable KC_3_TSUKI "オリジナル情報(最終チェック済データ)個人事項: 3出生年月(月)"
capture label variable KC_4_1_SHUGAKU "オリジナル情報(最終チェック済データ)個人事項: 4(1)就学状況"
capture label variable KC_4_1_JIKI "オリジナル情報(最終チェック済データ)個人事項: 4(1)卒業時期(区分)"
capture label variable KC_4_1_GENGO "オリジナル情報(最終チェック済データ)個人事項: 4(1)卒業時期(元号)"
capture label variable KC_4_1_NEN "オリジナル情報(最終チェック済データ)個人事項: 4(1)卒業時期(年)"
capture label variable KC_4_2_GAKKO "オリジナル情報(最終チェック済データ)個人事項: 4(2)学校区分"
capture label variable KC_5_1_GENGO "オリジナル情報(最終チェック済データ)個人事項: 5(1)居住開始時期(区分・元号)"
capture label variable KC_5_1_NEN "オリジナル情報(最終チェック済データ)個人事項: 5(1)居住開始時期(年)"
capture label variable KC_5_1_TSUKI "オリジナル情報(最終チェック済データ)個人事項: 5(1)居住開始時期(月)"
capture label variable KC_5_2_RIYU "オリジナル情報(最終チェック済データ)個人事項: 5(2)居住理由"
capture label variable KC_5_3_ZENJUKBN "オリジナル情報(最終チェック済データ)個人事項: 5(3)前住地(区分)"
capture label variable KC_5_3_ZENJUKEN "オリジナル情報(最終チェック済データ)個人事項: 5(3)前住地(都道府県)"
capture label variable KC_6_SHUNYUMAIN "オリジナル情報(最終チェック済データ)個人事項: 6収入の種類(主)"
capture label variable KC_6_SHUNYU_1 "オリジナル情報(最終チェック済データ)個人事項: 6収入の種類(1)賃金・給料"
capture label variable KC_6_SHUNYU_2 "オリジナル情報(最終チェック済データ)個人事項: 6収入の種類(2)事業収入"
capture label variable KC_6_SHUNYU_3 "オリジナル情報(最終チェック済データ)個人事項: 6収入の種類(3)内職収入"
capture label variable KC_6_SHUNYU_4 "オリジナル情報(最終チェック済データ)個人事項: 6収入の種類(4)年金・恩給"
capture label variable KC_6_SHUNYU_5 "オリジナル情報(最終チェック済データ)個人事項: 6収入の種類(5)雇用保険"
capture label variable KC_6_SHUNYU_6 "オリジナル情報(最終チェック済データ)個人事項: 6収入の種類(6)その他の給付"
capture label variable KC_6_SHUNYU_7 "オリジナル情報(最終チェック済データ)個人事項: 6収入の種類(7)仕送り"
capture label variable KC_6_SHUNYU_8 "オリジナル情報(最終チェック済データ)個人事項: 6収入の種類(8)家賃・地代"
capture label variable KC_6_SHUNYU_9 "オリジナル情報(最終チェック済データ)個人事項: 6収入の種類(9)利子・配当"
capture label variable KC_6_SHUNYU_10 "オリジナル情報(最終チェック済データ)個人事項: 6収入の種類(10)その他"
capture label variable KC_7_SHUGYO "オリジナル情報(最終チェック済データ)個人事項: 7就業状態"
capture label variable KC_A1_CHII "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A1従業上の地位"
capture label variable KC_A1_2_KIGYO "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A1-2起業の有無"
capture label variable KC_A1_3_KOYOKIKAN "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A1-3雇用契約期間の有無"
capture label variable KC_A1_4_KOSHIN "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A1-4契約更新の有無"
capture label variable KC_A1_4_KOSHINSU "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A1-4契約更新の回数"
capture label variable KC_A2_1_SOSHIKI "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A2(1)経営組織"
capture label variable KC_A2_23_SANGS "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A2(2)(3)産業"
capture label variable KC_A3_SHOKS "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A3職業"
capture label variable KC_A4_KIBO "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A4従業者規模"
capture label variable KC_A5_1_NISSU "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A5(1)年間日数"
capture label variable KC_A5_2_KISOKU "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A5(2)規則性"
capture label variable KC_A5_3_JIKAN "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A5(3)週時間"
capture label variable KC_A6_SHOTOKU "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A6年間所得"
capture label variable KC_A7_STARTGENGO "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A7就業開始時期(元号)"
capture label variable KC_A7_STARTNEN "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A7就業開始時期(年)"
capture label variable KC_A7_STARTTSUKI "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A7就業開始時期(月)"
capture label variable KC_A8_SHUGYORIYU "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A8就業理由"
capture label variable KC_A9_KEITAIRIYU_1 "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A9雇用形態理由(1)都合のよい時間"
capture label variable KC_A9_KEITAIRIYU_2 "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A9雇用形態理由(2)家計の補助・学費"
capture label variable KC_A9_KEITAIRIYU_3 "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A9雇用形態理由(3)家事・育児・介護"
capture label variable KC_A9_KEITAIRIYU_4 "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A9雇用形態理由(4)通勤時間"
capture label variable KC_A9_KEITAIRIYU_5 "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A9雇用形態理由(5)専門的な技能"
capture label variable KC_A9_KEITAIRIYU_6 "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A9雇用形態理由(6)正社員がない"
capture label variable KC_A9_KEITAIRIYU_7 "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A9雇用形態理由(7)その他"
capture label variable KC_A9_KEITAIRIYUMAIN "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A9雇用形態理由(主)"
capture label variable KC_A10_CHOSEI "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A10時間・日数の調整"
capture label variable KC_A11_KEIZOKUKIBO "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A11継続希望"
capture label variable KC_A11_2_TENSHOKURIYU "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A11-2転職希望理由"
capture label variable KC_A11_3_TENSHOKUKEITAI "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A11-3転職希望形態"
capture label variable KC_A11_4_KYUSHOKU "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A11-4求職活動"
capture label variable KC_A12_KIBOJIKAN "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A12就業時間希望"
capture label variable KC_A13_FUKUKBN "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A13副業(有無・従業上の地位)"
capture label variable KC_A14_FUKUSANGD "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A14副業の産業"
capture label variable KC_A15_ZENSHUGYO "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A151年前の就業状態"
capture label variable KC_A16_ZENSHUGYOUMU "オリジナル情報(最終チェック済データ)Aふだん仕事をしている人: A16前職の有無"
capture label variable KC_B1_KIBOUMU "オリジナル情報(最終チェック済データ)Bふだん仕事をしていない人: B1就業希望の有無"
capture label variable KC_B2_KIBORIYU "オリジナル情報(最終チェック済データ)Bふだん仕事をしていない人: B2就業希望の理由"
capture label variable KC_B3_KIBOSHOKUSHU "オリジナル情報(最終チェック済データ)Bふだん仕事をしていない人: B3就業希望職種"
capture label variable KC_B4_KIBOKEITAI "オリジナル情報(最終チェック済データ)Bふだん仕事をしていない人: B4就業希望形態"
capture label variable KC_B5_KYUSHOKU "オリジナル情報(最終チェック済データ)Bふだん仕事をしていない人: B5求職活動"
capture label variable KC_B6_HIKYUSHOKURIYU "オリジナル情報(最終チェック済データ)Bふだん仕事をしていない人: B6非求職の理由"
capture label variable KC_B7_KIKANKBN "オリジナル情報(最終チェック済データ)Bふだん仕事をしていない人: B7求職期間(区分)"
capture label variable KC_B7_KIKANNEN "オリジナル情報(最終チェック済データ)Bふだん仕事をしていない人: B7求職期間(年)"
capture label variable KC_B7_KIKANTSUKI "オリジナル情報(最終チェック済データ)Bふだん仕事をしていない人: B7求職期間(月)"
capture label variable KC_B8_KIBOJIKI "オリジナル情報(最終チェック済データ)Bふだん仕事をしていない人: B8就業希望時期"
capture label variable KC_B9_HIKIBORIYU "オリジナル情報(最終チェック済データ)Bふだん仕事をしていない人: B9就業非希望理由"
capture label variable KC_B10_ZENSHUGYO "オリジナル情報(最終チェック済データ)Bふだん仕事をしていない人: B101年前の就業状態"
capture label variable KC_B11_ZENSHUGYOUMU "オリジナル情報(最終チェック済データ)Bふだん仕事をしていない人: B11前職の有無"
capture label variable KC_C1_ENDJIKI "オリジナル情報(最終チェック済データ)C前の仕事について: C1離職時期(区分)"
capture label variable KC_C1_ENDGENGO "オリジナル情報(最終チェック済データ)C前の仕事について: C1離職時期(元号)"
capture label variable KC_C1_ENDNEN "オリジナル情報(最終チェック済データ)C前の仕事について: C1離職時期(年)"
capture label variable KC_C1_ENDTSUKI "オリジナル情報(最終チェック済データ)C前の仕事について: C1離職時期(月)"
capture label variable KC_C2_KIKANKBN "オリジナル情報(最終チェック済データ)C前の仕事について: C2就業期間(区分)"
capture label variable KC_C2_KIKANNEN "オリジナル情報(最終チェック済データ)C前の仕事について: C2就業期間(年)"
capture label variable KC_C2_KIKANTSUKI "オリジナル情報(最終チェック済データ)C前の仕事について: C2就業期間(か月)"
capture label variable KC_C3_RIYU "オリジナル情報(最終チェック済データ)C前の仕事について: C3離職理由"
capture label variable KC_C4_CHII "オリジナル情報(最終チェック済データ)C前の仕事について: C4前職の従業上の地位"
capture label variable KC_C5_KOYOKIKAN "オリジナル情報(最終チェック済データ)C前の仕事について: C5前職の雇用契約期間"
capture label variable KC_C6_SANGD "オリジナル情報(最終チェック済データ)C前の仕事について: C6前職の産業"
capture label variable KC_C7_SHOKD "オリジナル情報(最終チェック済データ)C前の仕事について: C7前職の職業"
capture label variable KC_D1_KBN "オリジナル情報(最終チェック済データ)D初職について: D1初職と現職・前職との関係"
capture label variable KC_D2_STARTGENGO "オリジナル情報(最終チェック済データ)D初職について: D2初職時期(元号)"
capture label variable KC_D2_STARTNEN "オリジナル情報(最終チェック済データ)D初職について: D2初職時期(年)"
capture label variable KC_D2_STARTTSUKI "オリジナル情報(最終チェック済データ)D初職について: D2初職時期(月)"
capture label variable KC_D3_CHII "オリジナル情報(最終チェック済データ)D初職について: D3初職の従業上の地位"
capture label variable KC_G1_NENSHU "オリジナル情報(最終チェック済データ)G世帯について: G1世帯の年間収入"
capture label variable KC_G2_15MIMANJININ "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の合計"
capture label variable KC_G2_15MIMANNENREI0 "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の内訳0歳"
capture label variable KC_G2_15MIMANNENREI1 "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の内訳1歳"
capture label variable KC_G2_15MIMANNENREI2 "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の内訳2歳"
capture label variable KC_G2_15MIMANNENREI3 "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の内訳3歳"
capture label variable KC_G2_15MIMANNENREI4 "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の内訳4歳"
capture label variable KC_G2_15MIMANNENREI5 "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の内訳5歳"
capture label variable KC_G2_15MIMANNENREI6 "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の内訳6歳"
capture label variable KC_G2_15MIMANNENREI7 "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の内訳7歳"
capture label variable KC_G2_15MIMANNENREI8 "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の内訳8歳"
capture label variable KC_G2_15MIMANNENREI9 "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の内訳9歳"
capture label variable KC_G2_15MIMANNENREI10 "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の内訳10歳"
capture label variable KC_G2_15MIMANNENREI11 "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の内訳11歳"
capture label variable KC_G2_15MIMANNENREI12 "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の内訳12歳"
capture label variable KC_G2_15MIMANNENREI13 "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の内訳13歳"
capture label variable KC_G2_15MIMANNENREI14 "オリジナル情報(最終チェック済データ)G世帯について: G215歳未満の内訳14歳"
capture label variable S_IPPAN "世帯に関する事項: 一般・単身世帯の別"
capture label variable S_KAZOKURUI12 "世帯に関する事項家族類型: 特定家族類型12区分"
capture label variable K_AGE "個人に関する事項年齢: 各歳"
capture label variable K_AGE5 "個人に関する事項年齢: 5歳階級"
capture label variable K_AGE10 "個人に関する事項年齢: 10歳階級"
capture label variable YH_KOKUCHO_SANSYO "サマリー付加情報: 産業小分類・国調分類符号(現職)"
capture label variable YH_KOKUCHO_SHOSYO "サマリー付加情報: 職業小分類・国調分類符号(現職)"
capture label variable YF_KOKUCHO_SANDAI "サマリー付加情報: 産業大分類・国調分類符号(副業)"
capture label variable Z_KOKUCHO_SANDAI "サマリー付加情報: 産業大分類・国調分類符号(前職)"
capture label variable Z_KOKUCHO_SHODAI "サマリー付加情報: 職業大分類・国調分類符号(前職)"
