/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2021/03/12 16:37:32
-----------------------------------------------------------------------------*/


capture label define CHO_YEAR 1992 "" 
capture label values CHO_YEAR CHO_YEAR

capture label define CHO_MONTH 10 "" 
capture label values CHO_MONTH CHO_MONTH

capture label define S_IPPAN 1 "一般世帯:15歳未満世帯人員を含めて世帯人員が2人以上の世帯" 2 "単身世帯:15歳未満世帯人員を含めても世帯人員が1人の世帯" 
capture label values S_IPPAN S_IPPAN

capture label define S_KAZOKURUI 1 "夫婦のみの世帯" 2 "夫婦と子供からなる世帯" 3 "夫婦と親からなる世帯" 4 "夫婦と子供と親からなる世帯" 5 "その他の世帯+単身世帯" 
capture label values S_KAZOKURUI S_KAZOKURUI

capture label define S_OMOSYU 1 "(調査:○D1)賃金・給料" 2 "農業収入" 3 "その他の事業収入" 4 "内職収入" 5 "家賃・地代" 6 "利子・配当" 7 "恩給・年金" 8 "雇用保険" 9 "その他(仕送りなど)" 
capture label values S_OMOSYU S_OMOSYU

capture label define S_JYU1 1 "(調査:○D1)賃金・給料" 
capture label values S_JYU1 S_JYU1

capture label define S_JYU2 2 "農業収入" 
capture label values S_JYU2 S_JYU2

capture label define S_JYU3 3 "その他の事業収入" 
capture label values S_JYU3 S_JYU3

capture label define S_JYU4 4 "内職収入" 
capture label values S_JYU4 S_JYU4

capture label define S_JYU5 5 "家賃・地代" 
capture label values S_JYU5 S_JYU5

capture label define S_JYU6 6 "利子・配当" 
capture label values S_JYU6 S_JYU6

capture label define S_JYU7 7 "恩給・年金" 
capture label values S_JYU7 S_JYU7

capture label define S_JYU8 8 "雇用保険" 
capture label values S_JYU8 S_JYU8

capture label define S_JYU9 9 "その他(仕送りなど)" 
capture label values S_JYU9 S_JYU9

capture label define S_SHOTOKU 1 "(調査:○D2)100万円未満" 2 "100~199万円" 3 "200~299万円" 4 "300~399万円" 5 "400~499万円" 6 "500~599万円" 7 "600~699万円" 8 "700~799万円" 9 "800~899万円" 10 "900~999万円" 11 "1000~1499万円" 12 "1500万円以上" 
capture label values S_SHOTOKU S_SHOTOKU

capture label define K_SEX 1 "(調査:○1)男" 2 "女" 
capture label values K_SEX K_SEX

capture label define K_TUZUKI 1 "(調査:○2)世帯主又は代表者" 2 "世帯主の配偶者" 3 "子" 4 "子の配偶者" 5 "孫" 6 "父母" 7 "祖父母" 8 "兄弟姉妹" 9 "他の親族" 10 "その他" 
capture label values K_TUZUKI K_TUZUKI

capture label define K_NENGO 1 "明治" 2 "大正" 3 "昭和" 
capture label values K_NENGO K_NENGO

capture label define K_TUKI 1 "1~9月" 2 "10~12月" 
capture label values K_TUKI K_TUKI

capture label define K_AGE5 1 "15~19歳" 2 "20~24歳" 3 "25~29歳" 4 "30~34歳" 5 "35~39歳" 6 "40~44歳" 7 "45~49歳" 8 "50~54歳" 9 "55~59歳" 10 "60~64歳" 11 "65~69歳" 12 "70~74歳" 13 "75歳以上" 
capture label values K_AGE5 K_AGE5

capture label define K_AGE10 1 "15~24歳" 2 "25~34歳" 3 "35~44歳" 4 "45~54歳" 5 "55~64歳" 6 "65歳以上" 
capture label values K_AGE10 K_AGE10

capture label define K_HAIGU 1 "(調査:○4)未婚" 2 "有配偶" 3 "死別・離別" 
capture label values K_HAIGU K_HAIGU

capture label define K_ZENJYU 1 "(調査:○5)現在の住居" 2 "同じ市区町村の別のところ" 3 "同じ都道府県内の別のところ" 4 "他の都道府県" 5 "外国" 
capture label values K_ZENJYU K_ZENJYU

capture label define K_SOTUGYO 1 "(調査:○6)在学中" 2 "卒業" 3 "在学したことがない" 
capture label values K_SOTUGYO K_SOTUGYO

capture label define K_GAKKO 1 "(調査:○6)小学・中学" 2 "高校・旧中" 3 "短大・高専" 4 "大学・大学院" 
capture label values K_GAKKO K_GAKKO

capture label define K_SYUGYO 1 "(調査:○問1)仕事を主にしている" 2 "家事が主で仕事もしている" 3 "通学が主で仕事もしている" 4 "家事通学以外が主で仕事もしている" 5 "家事をしている" 6 "通学をしている" 7 "その他" 
capture label values K_SYUGYO K_SYUGYO

capture label define YH_JYUTII 1 "(調査:○A2)常雇(一般常雇)" 2 "臨時雇" 3 "日雇" 4 "会社団体等の役員(民間の役員)" 5 "雇人あり" 6 "雇人なし" 7 "自家営業の手伝い" 8 "家庭で内職" 
capture label values YH_JYUTII YH_JYUTII

capture label define YH_KOSHO7 1 "民間の役員" 2 "正規の職員" 3 "パート" 4 "アルバイト" 5 "嘱託など" 6 "派遣社員" 7 "その他" 
capture label values YH_KOSHO7 YH_KOSHO7

capture label define YH_KEIEI 1 "(調査:○A3)個人" 2 "会社" 3 "その他の法人・団体" 4 "官公庁" 
capture label values YH_KEIEI YH_KEIEI

capture label define YH_NOHINOU 1 "農林業" 2 "非農林業" 
capture label values YH_NOHINOU YH_NOHINOU

capture label define YH_SAN3 1 "第1次産業" 2 "第2次産業" 3 "第3次産業" 
capture label values YH_SAN3 YH_SAN3

capture label define YH_SANDAI 1 "A農業" 2 "B林業" 3 "C漁業" 4 "D鉱業" 5 "E建設業" 6 "F製造業" 7 "G電気・ガス・熱供給・水道業" 8 "H運輸・通信業" 9 "I卸売・小売業,飲食店" 10 "J金融・保険業,不動産業" 11 "Lサービス業" 12 "M公務(他に分類されないもの)" 
capture label values YH_SANDAI YH_SANDAI

capture label define YH_SANM 1 "農業" 2 "林業" 3 "漁業" 4 "鉱業" 5 "建設業" 6 "繊維工業" 7 "化学諸工業" 8 "金属工業" 9 "機械工業" 10 "その他の工業" 11 "電気・ガス・熱供給・水道業" 12 "運輸業" 13 "通信業" 14 "卸売業" 15 "小売業" 16 "飲食店" 17 "金融・保険業" 18 "不動産業" 19 "対個人サービス業" 20 "対事業所サービス業" 21 "映画・娯楽業" 22 "整備・修理業" 23 "医療業" 24 "教育" 25 "他に分類されない専門サービス業" 26 "その他のサービス業" 27 "公務(他に分類されないもの)" 
capture label values YH_SANM YH_SANM

capture label define YH_SANCHU 1 "01農業" 2 "02林業" 3 "03漁業" 5 "05鉱業" 9 "09建設業" 12 "12食料品・飲料・たばこ製造業" 14 "14繊維工業" 16 "16木材・木製品・家具製造業" 18 "18パルプ・紙・紙加工品製造業" 19 "19出版・印刷・同関連産業" 20 "20化学工業" 25 "25窯業・土石製品製造業" 26 "26鉄鋼業" 27 "27非鉄金属製造業" 28 "28金属製品製造業" 29 "29一般機械器具製造業" 30 "30電気機械器具製造業" 31 "31輸送用機械器具製造業" 32 "32精密機械器具製造業" 34 "34その他の製造業" 36 "36電気・ガス・熱供給・水道業" 40 "40鉄道業" 41 "41運送・倉庫業" 47 "47通信業" 49 "49卸売業" 55 "55飲食料品小売業" 58 "58その他の小売業" 59 "59飲食店" 61 "61金融・保険業" 69 "69不動産業" 73 "73対個人サービス業" 77 "77映画・娯楽業" 81 "81整備・修理業" 83 "83対事業所サービス業" 87 "87医療業" 91 "91教育" 94 "94他に分類されない専門サービス業" 95 "95その他のサービス業" 97 "97公務(他に分類されないもの)" 
capture label values YH_SANCHU YH_SANCHU

capture label define YH_SHODAI 1 "専門的・技術的職業従事者" 2 "管理的職業従事者" 3 "事務従事者" 4 "販売従事者" 5 "サービス職業従事者" 6 "保安職業従事者" 7 "農林漁業作業者" 8 "運輸・通信従事者" 9 "技能工,採掘・製造・建設作業者及び労務作業者" 
capture label values YH_SHODAI YH_SHODAI

capture label define YH_SHOM 0 "(調査:○)00専門的・技術的職業従事者" 10 "10管理的職業従事者" 20 "20事務従事者" 30 "30販売従事者" 40 "40サービス職業従事者" 50 "50保安職業従事者" 60 "60農林漁業作業者" 70 "70運輸・通信従事者" 80 "80採掘作業者" 82 "82金属,機械,化学等技能的職業従事者" 89 "89食料品,繊維製品等の技能的職業作業者" 99 "99その他の技能的職業作業者" 
capture label values YH_SHOM YH_SHOM

capture label define YH_KAIKYUU 1 "(調査:○A5)1~4人" 2 "5~9人" 3 "10~19人" 4 "20~29人" 5 "30~49人" 6 "50~99人" 7 "100~299人" 8 "300~499人" 9 "500~999人" 10 "1000人以上" 11 "官公庁" 
capture label values YH_KAIKYUU YH_KAIKYUU

capture label define YH_NISSU 1 "(調査:○A6)50日未満" 2 "50~99日" 3 "100~149日" 4 "150~199日" 5 "200~249日" 6 "250日以上" 
capture label values YH_NISSU YH_NISSU

capture label define YH_JYUGYO 1 "(調査:○A6)不規則" 2 "ある季節だけ" 3 "だいたい規則的" 
capture label values YH_JYUGYO YH_JYUGYO

capture label define YH_JIKAN 1 "(調査:○A6)15時間未満" 2 "15~21時間" 3 "22~34時間" 4 "35~42時間" 5 "43~45時間" 6 "46~48時間" 7 "49~59時間" 8 "60時間以上" 
capture label values YH_JIKAN YH_JIKAN

capture label define YH_SHOTOKU 1 "(調査:○A7)収入なし・50万円未満" 2 "50~99万円" 3 "100~149万円" 4 "150~199万円" 5 "200~249万円" 6 "250~299万円" 7 "300~399万円" 8 "400~499万円" 9 "500~699万円" 10 "700~999万円" 11 "1000~1499万円" 12 "1500万円以上" 
capture label values YH_SHOTOKU YH_SHOTOKU

capture label define YH_SYUISIKI 1 "(調査:○A8)この仕事を続けたい" 2 "副業をもちたい" 3 "転職したい" 4 "仕事をやめたい" 
capture label values YH_SYUISIKI YH_SYUISIKI

capture label define YH_SYUZOGEN 1 "(調査:○A8・2)今のままでよい" 2 "時間を増やしたい" 3 "時間を減らしたい" 
capture label values YH_SYUZOGEN YH_SYUZOGEN

capture label define YH_SYURIYU 1 "(調査:○A9)一時的についた仕事だから" 2 "収入が少ないから" 3 "将来性がないから" 4 "定年などに備えて" 5 "時間的・肉体的に負担が大きいから" 6 "知識や技能を生かしたいから" 7 "余暇を増やしたいから" 8 "家事の都合から" 9 "その他" 
capture label values YH_SYURIYU YH_SYURIYU

capture label define YH_SYUKEITAI 1 "(調査:○A10)正規の職員・従業員として雇われたい" 2 "パート・アルバイトの仕事をしたい" 3 "自分で事業をしたい" 4 "自家営業を手伝いたい" 5 "家庭で内職をしたい" 6 "その他" 
capture label values YH_SYUKEITAI YH_SYUKEITAI

capture label define YH_KATUDO 1 "(調査:○A11)探している" 2 "開業の準備をしている" 3 "何もしていない" 
capture label values YH_KATUDO YH_KATUDO

capture label define YF_FUKU 1 "(調査:○A12)別の仕事もしている" 2 "今はしていないがある時期にはしている" 3 "別の仕事はしていない" 
capture label values YF_FUKU YF_FUKU

capture label define YF_JYUTII 1 "(調査:○A13)雇われている" 2 "会社団体の役員" 3 "自営業主" 4 "自家営業の手伝い" 5 "家庭内で内職" 
capture label values YF_JYUTII YF_JYUTII

capture label define YF_NOHINOU 1 "農林業" 2 "非農林業" 
capture label values YF_NOHINOU YF_NOHINOU

capture label define YF_SANDAI 1 "A農業" 2 "B林業" 3 "C漁業" 4 "D鉱業" 5 "E建設業" 6 "F製造業" 7 "G電気・ガス・熱供給・水道業" 8 "H運輸・通信業" 9 "I卸売・小売業,飲食店" 10 "J金融・保険業,不動産業" 11 "Lサービス業" 12 "M公務(他に分類されないもの)" 
capture label values YF_SANDAI YF_SANDAI

capture label define YF_SANCHU 1 "01農業" 2 "02林業" 3 "03漁業" 5 "05鉱業" 9 "09建設業" 12 "12食料品・飲料・たばこ製造業" 14 "14繊維工業" 16 "16木材・木製品・家具製造業" 18 "18パルプ・紙・紙加工品製造業" 19 "19出版・印刷・同関連産業" 20 "20化学工業" 25 "25窯業・土石製品製造業" 26 "26鉄鋼業" 27 "27非鉄金属製造業" 28 "28金属製品製造業" 29 "29一般機械器具製造業" 30 "30電気機械器具製造業" 31 "31輸送用機械器具製造業" 32 "32精密機械器具製造業" 34 "34その他の製造業" 36 "36電気・ガス・熱供給・水道業" 40 "40鉄道業" 41 "41運送・倉庫業" 47 "47通信業" 49 "49卸売業" 55 "55飲食料品小売業" 58 "58その他の小売業" 59 "59飲食店" 61 "61金融・保険業" 69 "69不動産業" 73 "73対個人サービス業" 77 "77映画・娯楽業" 81 "81整備・修理業" 83 "83対事業所サービス業" 87 "87医療業" 91 "91教育" 94 "94他に分類されない専門サービス業" 95 "95その他のサービス業" 97 "97公務(他に分類されないもの)" 
capture label values YF_SANCHU YF_SANCHU

capture label define YZ_KEIZOKU 1 "(調査:○A15)一年前にも現在の仕事をしていた" 2 "一年前には仕事をしていなかった" 
capture label values YZ_KEIZOKU YZ_KEIZOKU

capture label define YZ_SYUGYO 1 "(調査:○A16)仕事を主にしていた" 2 "家事・通学などのかたわらにしていた" 3 "家事をしていた" 4 "通学をしていた" 5 "その他" 
capture label values YZ_SYUGYO YZ_SYUGYO

capture label define YZ_SYURIYU 1 "(調査:○A17)失業していたから" 2 "学校を卒業したから" 3 "収入を得たかったから" 4 "知識や技能を生かしたかったから" 5 "社会に出たかったから" 6 "余暇ができたから" 7 "その他" 
capture label values YZ_SYURIYU YZ_SYURIYU

capture label define YZ_ZENUMU 1 "(調査:○A18)前職あり" 2 "前職なし" 
capture label values YZ_ZENUMU YZ_ZENUMU

capture label define M_SYUKIBOU 1 "(調査:○B2)仕事をしたいと思っている" 2 "仕事をしたいと思っていない" 
capture label values M_SYUKIBOU M_SYUKIBOU

capture label define M_SYURIYU 1 "(調査:○B3)失業していたから" 2 "学校を卒業したから" 3 "収入を得たかったから" 4 "知識や技能を生かしたかったから" 5 "社会に出たかったから" 6 "余暇ができたから" 7 "その他" 
capture label values M_SYURIYU M_SYURIYU

capture label define M_SYUSIGOTO 1 "(調査:○B4)仕事を主にしていきたい" 2 "家事や通学などのかたわらにしたい" 
capture label values M_SYUSIGOTO M_SYUSIGOTO

capture label define M_SYUKEITAI 1 "(調査:○B5)正規の職員・従業員として雇られたい" 2 "パート・アルバイトの仕事をしたい" 3 "自分で事業をしたい" 4 "自家営業を手伝いたい" 5 "家庭で内職をしたい" 6 "その他" 
capture label values M_SYUKEITAI M_SYUKEITAI

capture label define M_KYUKATUDO 1 "(調査:○B6)探している" 2 "開業の準備をしている" 3 "何もしていない" 
capture label values M_KYUKATUDO M_KYUKATUDO

capture label define M_KYUHIRIYU 1 "(調査:○B7)探したが見つからなかった" 2 "自分の希望する仕事がありそうにない" 3 "自分の知識・能力に自信がない" 4 "病気・高齢のため" 5 "家事・育児や通学などで忙しい" 6 "家族の介護・看護のため" 7 "急いで仕事につく必要がない" 8 "その他" 
capture label values M_KYUHIRIYU M_KYUHIRIYU

capture label define M_KYUHOHO 1 "(調査:○B8)公共職業安定所等に申し込む" 2 "事業所に直接応募" 3 "知人などに相談・あっせん依頼" 4 "広告・求人情報誌等" 5 "人材派遣企業に登録" 6 "事業用資金の調達等" 7 "その他" 
capture label values M_KYUHOHO M_KYUHOHO

capture label define M_KYUKIKAN 1 "(調査:○B9)1か月未満" 2 "1か月以上3か月未満" 3 "3か月以上6か月未満" 4 "6か月以上1年未満" 5 "1年以上2年未満" 6 "2年以上" 
capture label values M_KYUKIKAN M_KYUKIKAN

capture label define M_KIBOJIKI 1 "(調査:○B10)すぐつくつもり" 2 "すぐではないがつくつもり" 3 "つくかどうかわからない" 
capture label values M_KIBOJIKI M_KIBOJIKI

capture label define M_ZSYUGYO 1 "(調査:○B11)家事をしていた" 2 "通学していた" 3 "その他" 4 "仕事をおもにしていた" 5 "家事・通学のかたわらにしていた" 
capture label values M_ZSYUGYO M_ZSYUGYO

capture label define M_ZENUMU 1 "(調査:○B12)ある" 2 "ない" 
capture label values M_ZENUMU M_ZENUMU

capture label define Z_RIJIKI2 1 "(調査:○C1)昭和41年以降" 2 "昭和40年以前" 
capture label values Z_RIJIKI2 Z_RIJIKI2

capture label define Z_RIJIKIK 1 "昭和" 2 "平成" 
capture label values Z_RIJIKIK Z_RIJIKIK

capture label define Z_RIYU 1 "(調査:○C2)人員整理・会社解散・倒産のため" 2 "一時的・不安定な仕事だったから" 3 "収入が少なかったから" 4 "労働条件が悪かったから" 5 "自分に向かない仕事だったから" 6 "家族の就職・転職・転勤及び事業所の移転のため" 7 "定年などのため" 8 "病気・高齢のため" 9 "結婚のため" 10 "育児のため" 11 "家族の介護・看護のため" 12 "その他" 
capture label values Z_RIYU Z_RIYU

capture label define Z_JYUTII 1 "(調査:○C3)常雇" 2 "臨時雇" 3 "日雇" 4 "会社・団体等の役員" 5 "雇人あり" 6 "雇人なし" 7 "自家営業の手伝い" 8 "家庭で内職" 
capture label values Z_JYUTII Z_JYUTII

capture label define Z_NOHINOU 1 "農林業" 2 "非農林業" 
capture label values Z_NOHINOU Z_NOHINOU

capture label define Z_SAN3 1 "第1次産業" 2 "第2次産業" 3 "第3次産業" 
capture label values Z_SAN3 Z_SAN3

capture label define Z_SANDAI 1 "A農業" 2 "B林業" 3 "C漁業" 4 "D鉱業" 5 "E建設業" 6 "F製造業" 7 "G電気・ガス・熱供給・水道業" 8 "H運輸・通信業" 9 "I卸売・小売業,飲食店" 10 "J金融・保険業,不動産業" 11 "Lサービス業" 12 "M公務(他に分類されないもの)" 
capture label values Z_SANDAI Z_SANDAI

capture label define Z_SANCHU 1 "01農業" 2 "02林業" 3 "03漁業" 5 "05鉱業" 9 "09建設業" 12 "12食料品・飲料・たばこ製造業" 14 "14繊維工業" 16 "16木材・木製品・家具製造業" 18 "18パルプ・紙・紙加工品製造業" 19 "19出版・印刷・同関連産業" 20 "20化学工業" 25 "25窯業・土石製品製造業" 26 "26鉄鋼業" 27 "27非鉄金属製造業" 28 "28金属製品製造業" 29 "29一般機械器具製造業" 30 "30電気機械器具製造業" 31 "31輸送用機械器具製造業" 32 "32精密機械器具製造業" 34 "34その他の製造業" 36 "36電気・ガス・熱供給・水道業" 40 "40鉄道業" 41 "41運送・倉庫業" 47 "47通信業" 49 "49卸売業" 55 "55飲食料品小売業" 58 "58その他の小売業" 59 "59飲食店" 61 "61金融・保険業" 69 "69不動産業" 73 "73対個人サービス業" 77 "77映画・娯楽業" 81 "81整備・修理業" 83 "83対事業所サービス業" 87 "87医療業" 91 "91教育" 94 "94他に分類されない専門サービス業" 95 "95その他のサービス業" 97 "97公務(他に分類されないもの)" 
capture label values Z_SANCHU Z_SANCHU

capture label define Z_SHODAI 1 "専門的・技術的職業従事者" 2 "管理的職業従事者" 3 "事務従事者" 4 "販売従事者" 5 "サービス職業従事者" 6 "保安職業従事者" 7 "農林漁業作業者" 8 "運輸・通信従事者" 9 "技能工,採掘・製造・建設作業者及び労務作業者" 
capture label values Z_SHODAI Z_SHODAI

capture label define Z_SHOM 0 "(調査:○)00専門的・技術的職業従事者" 10 "10管理的職業従事者" 20 "20事務従事者" 30 "30販売従事者" 40 "40サービス職業従事者" 50 "50保安職業従事者" 60 "60農林漁業作業者" 70 "70運輸・通信従事者" 80 "80採掘作業者" 82 "82金属,機械,化学等技能的職業従事者" 89 "89食料品,繊維製品等の技能的職業作業者" 99 "99その他の技能的職業作業者" 
capture label values Z_SHOM Z_SHOM

capture label define Z_KAIKYUU 1 "(調査:○C6)1~4人" 2 "5~9人" 3 "10~19人" 4 "20~29人" 5 "30~49人" 6 "50~99人" 7 "100~299人" 8 "300~499人" 9 "500~999人" 10 "1000人以上" 11 "官公庁" 
capture label values Z_KAIKYUU Z_KAIKYUU

capture label define Z_KEINEN 0 "(調査:○C7)0年" 1 "1~2年" 2 "3~4年" 3 "5~9年" 4 "10~14年" 5 "15~19年" 6 "20~24年" 7 "25~29年" 8 "30年以上" 
capture label values Z_KEINEN Z_KEINEN

