/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2021/03/12 16:37:32
-----------------------------------------------------------------------------*/


capture label define S_KAZOKURUI12 1 "夫婦のみの世帯" 2 "夫婦と両親からなる世帯" 3 "夫婦とひとり親から成る世帯" 4 "夫婦と子供から成る世帯" 5 "夫婦、子供と両親から成る世帯" 6 "夫婦、子供とひとり親から成る世帯" 7 "ひとり親と子供からなる世帯" 8 "兄弟姉妹からなる世帯" 9 "単身世帯" 
capture label values S_KAZOKURUI12 S_KAZOKURUI12

capture label define S_OMOSYU 1 "賃金・給料" 2 "農業収入" 3 "その他の事業収入" 4 "内職収入" 5 "家賃・地代" 6 "利子・配当" 7 "恩給・年金" 8 "雇用保険" 9 "仕送り" 
capture label values S_OMOSYU S_OMOSYU

capture label define S_JYU1 1 "記入あり" 0 "記入なし" 
capture label values S_JYU1 S_JYU1

capture label define S_JYU2 1 "記入あり" 0 "記入なし" 
capture label values S_JYU2 S_JYU2

capture label define S_JYU3 1 "記入あり" 0 "記入なし" 
capture label values S_JYU3 S_JYU3

capture label define S_JYU4 1 "記入あり" 0 "記入なし" 
capture label values S_JYU4 S_JYU4

capture label define S_JYU5 1 "記入あり" 0 "記入なし" 
capture label values S_JYU5 S_JYU5

capture label define S_JYU6 1 "記入あり" 0 "記入なし" 
capture label values S_JYU6 S_JYU6

capture label define S_JYU7 1 "記入あり" 0 "記入なし" 
capture label values S_JYU7 S_JYU7

capture label define S_JYU8 1 "記入あり" 0 "記入なし" 
capture label values S_JYU8 S_JYU8

capture label define S_JYU9 1 "記入あり" 0 "記入なし" 
capture label values S_JYU9 S_JYU9

capture label define S_JYU10 1 "記入あり" 0 "記入なし" 
capture label values S_JYU10 S_JYU10

capture label define S_SYUNYU 1 "100万円未満" 2 "100~199万円" 3 "200~299万円" 4 "300~399万円" 5 "400~499万円" 6 "500~599万円" 7 "600~699万円" 8 "700~799万円" 9 "800~899万円" 
capture label values S_SYUNYU S_SYUNYU

capture label define K_TUZUKI 1 "世帯主" 2 "世帯主の配偶者" 3 "子" 4 "子の配偶者" 5 "孫" 6 "世帯主の父母" 7 "世帯主の配偶者の父母" 8 "祖父母" 9 "兄弟姉妹" 
capture label values K_TUZUKI K_TUZUKI

capture label define K_AGE5 1 "15~19歳" 2 "20~24歳" 3 "25~29歳" 4 "30~34歳" 5 "35~39歳" 6 "40~44歳" 7 "45~49歳" 8 "50~54歳" 9 "55~59歳" 
capture label values K_AGE5 K_AGE5

capture label define K_GRIYU 1 "仕事につくため" 2 "仕事をやめたため" 3 "転勤のため" 4 "その他" 5 "仕事につくため" 6 "仕事をやめたため" 7 "転勤のため" 8 "その他" 9 "通学のため" 
capture label values K_GRIYU K_GRIYU

capture label define YH_SANDAI 1 "農業" 2 "林業" 3 "漁業" 4 "鉱業" 5 "建設業" 6 "製造業" 7 "電気・ガス・熱供給・水道業" 8 "情報通信業" 9 "運輸業" 
capture label values YH_SANDAI YH_SANDAI

capture label define YH_SANCHU 1 "農業" 2 "林業" 3 "漁業" 4 "水産養殖業" 5 "鉱業" 9 "建設業" 
capture label values YH_SANCHU YH_SANCHU

capture label define YH_SHODAI 1 "専門的・技術的職業従事者" 2 "管理的職業従事者" 3 "事務従事者" 4 "販売従事者" 5 "サービス職業従事者" 6 "保安職業従事者" 7 "農林漁業作業者" 8 "運輸・通信従事者" 9 "技能工,採掘・製造・建設作業及び労務従事者" 
capture label values YH_SHODAI YH_SHODAI

capture label define YH_SHOCHU 0 "科学研究者" 
capture label values YH_SHOCHU YH_SHOCHU

capture label define YH_JYUKIBO 1 "1~4人" 2 "5~9人" 3 "10~19人" 4 "20~29人" 5 "30~49人" 6 "50~99人" 7 "100~299人" 8 "300~499人" 9 "500~999人" 
capture label values YH_JYUKIBO YH_JYUKIBO

capture label define YH_JIKAN 1 "15時間未満" 2 "15~19時間" 3 "20~21時間" 4 "22~29時間" 5 "30~34時間" 6 "35~42時間" 7 "43~45時間" 8 "46~48時間" 9 "49~59時間" 
capture label values YH_JIKAN YH_JIKAN

capture label define YH_SYUNYU 1 "収入なし,50万円未満" 2 "50~99万円" 3 "100~149万円" 4 "150~199万円" 5 "200~249万円" 6 "250~299万円" 7 "300~399万円" 8 "400~499万円" 9 "500~599万円" 
capture label values YH_SYUNYU YH_SYUNYU

capture label define YF_SANCHU 1 "農業" 2 "林業" 3 "漁業" 4 "水産養殖業" 5 "鉱業" 9 "建設業" 
capture label values YF_SANCHU YF_SANCHU

capture label define M_SHOKUSHU 1 "製造・生産工程" 2 "建設・労務" 3 "運輸・通信職" 4 "営業・販売職" 5 "サービス業" 6 "専門・技術職" 7 "管理的職業" 8 "事務職" 9 "その他(保安職など)" 
capture label values M_SHOKUSHU M_SHOKUSHU

capture label define Z_RIRIYU 1 "人員整理・勧奨退職のため" 2 "会社倒産・事業所閉鎖" 3 "事業不振・先行き不安" 4 "一時的・不安定な仕事だったから" 5 "収入が少なかったから" 6 "労働条件が悪かったから" 7 "自分に向かない仕事だったから" 8 "家族の就職・転職・転勤及び事業所の移転のため" 9 "定年などのため" 
capture label values Z_RIRIYU Z_RIRIYU

capture label define Z_SANCHU 1 "農業" 2 "林業" 3 "漁業" 4 "水産養殖業" 5 "鉱業" 9 "建設業" 
capture label values Z_SANCHU Z_SANCHU

capture label define Z_SYOCHU 0 "科学研究者" 
capture label values Z_SYOCHU Z_SYOCHU

capture label define Z_JYUKIBO 1 "1~4人" 2 "5~9人" 3 "10~19人" 4 "20~29人" 5 "30~49人" 6 "50~99人" 7 "100~299人" 8 "300~499人" 9 "500~999人" 
capture label values Z_JYUKIBO Z_JYUKIBO

