/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2021/03/12 16:37:31
-----------------------------------------------------------------------------*/


capture label variable RES_NENTUKI "調査に関する事項: 調査実施年月"
capture label variable NK_CHOKEN "データ抜き出し情報調査区符号: 都道府県番号"
capture label variable NK_KENNAI "データ抜き出し情報調査区符号: 都道府県内一連番号"
capture label variable NK_SETAI1 "データ抜き出し情報世帯番号: 居住者の有無(世帯番号)"
capture label variable NK_SETAI2 "データ抜き出し情報世帯番号: 抽出単位番号(世帯番号)"
capture label variable NK_SETAI3 "データ抜き出し情報世帯番号: 世帯一連番号(世帯番号)"
capture label variable NK_SETAIIN "データ抜き出し情報: 世帯員番号"
capture label variable C_KEN "所在地に関する事項市区町村情報市区町村コード調査実施時: 都道府県(調査実施時)"
capture label variable C_CITY "所在地に関する事項市区町村情報市区町村コード調査実施時: 市区町村(調査実施時)"
capture label variable var1 "乗率: オリジナルデータか否か"
capture label variable R_RITSUTYPE "乗率: 乗率の種類"
capture label variable R_KEN "乗率: 都道府県番号"
capture label variable R_RITSUCITYNUM "乗率: 表章市用乗率の種類"
capture label variable R_RITSUBLKNUM "乗率: 県内経済圏用乗率の種類"
capture label variable R_SHUKEI "乗率: 集計用乗率"
capture label variable KC_JININ "オリジナル情報(最終チェック済データ)世帯事項調査員記入欄: 世帯人員(15歳以上)"
capture label variable KC_NENSYU "オリジナル情報(最終チェック済データ)世帯事項G_世帯について: G1_世帯全体の年間収入"
capture label variable KC_MIMAN15 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員: G2_15歳未満の合計"
capture label variable KC_NENREI0 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員G2_15歳未満各歳別人員: G2_0歳"
capture label variable KC_NENREI1 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員G2_15歳未満各歳別人員: G2_1歳"
capture label variable KC_NENREI2 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員G2_15歳未満各歳別人員: G2_2歳"
capture label variable KC_NENREI3 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員G2_15歳未満各歳別人員: G2_3歳"
capture label variable KC_NENREI4 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員G2_15歳未満各歳別人員: G2_4歳"
capture label variable KC_NENREI5 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員G2_15歳未満各歳別人員: G2_5歳"
capture label variable KC_NENREI6 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員G2_15歳未満各歳別人員: G2_6歳"
capture label variable KC_NENREI7 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員G2_15歳未満各歳別人員: G2_7歳"
capture label variable KC_NENREI8 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員G2_15歳未満各歳別人員: G2_8歳"
capture label variable KC_NENREI9 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員G2_15歳未満各歳別人員: G2_9歳"
capture label variable KC_NENREI10 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員G2_15歳未満各歳別人員: G2_10歳"
capture label variable KC_NENREI11 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員G2_15歳未満各歳別人員: G2_11歳"
capture label variable KC_NENREI12 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員G2_15歳未満各歳別人員: G2_12歳"
capture label variable KC_NENREI13 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員G2_15歳未満各歳別人員: G2_13歳"
capture label variable KC_NENREI14 "オリジナル情報(最終チェック済データ)世帯事項G_世帯についてG2_15歳未満の世帯人員G2_15歳未満各歳別人員: G2_14歳"
capture label variable KC_SEX "オリジナル情報(最終チェック済データ)個人事項: 1_男女の別"
capture label variable KC_HAIGU "オリジナル情報(最終チェック済データ)個人事項: 1_配偶者の有無"
capture label variable KC_TUZUKI "オリジナル情報(最終チェック済データ)個人事項: 2_続き柄"
capture label variable KC_GENGO "オリジナル情報(最終チェック済データ)個人事項3_出生の年月: 3_出生の年月(元号)"
capture label variable KC_NEN "オリジナル情報(最終チェック済データ)個人事項3_出生の年月: 3_出生の年月(年)"
capture label variable KC_TUKI "オリジナル情報(最終チェック済データ)個人事項3_出生の年月: 3_出生の年月(月)"
capture label variable KC_KYOIKU "オリジナル情報(最終チェック済データ)個人事項4_教育4(1)_就学状況: 4(1)_就学区分"
capture label variable KC_SOTUJIKI "オリジナル情報(最終チェック済データ)個人事項4_教育4(1)_就学状況: 4(1)_卒業年次区分"
capture label variable KC_SOTUGENGO "オリジナル情報(最終チェック済データ)個人事項4_教育4(1)_就学状況: 4(1)_卒業年次(元号)"
capture label variable KC_SOTUNEN "オリジナル情報(最終チェック済データ)個人事項4_教育4(1)_就学状況: 4(1)_卒業年次(年)"
capture label variable KC_GAKKO "オリジナル情報(最終チェック済データ)個人事項4_教育: 4(2)_学校区分"
capture label variable KC_JUKYOGENGO "オリジナル情報(最終チェック済データ)個人事項5_居住地について5(1)_居住開始時期: 5(1)_居住開始時期区分"
capture label variable KC_JUKYONEN "オリジナル情報(最終チェック済データ)個人事項5_居住地について5(1)_居住開始時期: 5(1)_居住開始時期(年)"
capture label variable KC_JUKYOTUKI "オリジナル情報(最終チェック済データ)個人事項5_居住地について5(1)_居住開始時期: 5(1)_居住開始時期(月)"
capture label variable KC_JUKYORIYU "オリジナル情報(最終チェック済データ)個人事項5_居住地について: 5(2)_居住理由"
capture label variable KC_ZENJKBN "オリジナル情報(最終チェック済データ)個人事項5_居住地について5(3)_前住地: 5(3)_前住地区分"
capture label variable KC_ZENJKEN "オリジナル情報(最終チェック済データ)個人事項5_居住地について5(3)_前住地: 5(3)_前住地都道府県番号(調査員記入欄)"
capture label variable KC_SYUNYUMAIN "オリジナル情報(最終チェック済データ)個人事項6_収入の種類: 6_収入の種類(主)"
capture label variable KC_SYUNYU1 "オリジナル情報(最終チェック済データ)個人事項6_収入の種類6_収入の種類(従): 6_賃金・給料(従)"
capture label variable KC_SYUNYU2 "オリジナル情報(最終チェック済データ)個人事項6_収入の種類6_収入の種類(従): 6_事業収入(従)"
capture label variable KC_SYUNYU3 "オリジナル情報(最終チェック済データ)個人事項6_収入の種類6_収入の種類(従): 6_内職収入(従)"
capture label variable KC_SYUNYU4 "オリジナル情報(最終チェック済データ)個人事項6_収入の種類6_収入の種類(従): 6_年金・恩給(従)"
capture label variable KC_SYUNYU5 "オリジナル情報(最終チェック済データ)個人事項6_収入の種類6_収入の種類(従): 6_雇用保険(従)"
capture label variable KC_SYUNYU6 "オリジナル情報(最終チェック済データ)個人事項6_収入の種類6_収入の種類(従): 6_その他の給付(従)"
capture label variable KC_SYUNYU7 "オリジナル情報(最終チェック済データ)個人事項6_収入の種類6_収入の種類(従): 6_仕送り(従)"
capture label variable KC_SYUNYU8 "オリジナル情報(最終チェック済データ)個人事項6_収入の種類6_収入の種類(従): 6_家賃・地代(従)"
capture label variable KC_SYUNYU9 "オリジナル情報(最終チェック済データ)個人事項6_収入の種類6_収入の種類(従): 6_利子・配当(従)"
capture label variable KC_SYUNYU10 "オリジナル情報(最終チェック済データ)個人事項6_収入の種類6_収入の種類(従): 6_その他(従)"
capture label variable KC_SYUGYO "オリジナル情報(最終チェック済データ)個人事項: 7_就業状態"
capture label variable KC_CHII "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A1_従業上の地位"
capture label variable KC_KIGYO "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A1-2_起業の有無"
capture label variable KC_KOYOKIKAN "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A1-3_雇用契約期間の有無・雇用契約期間"
capture label variable KC_KOUSHIN "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A1-4_契約更新の有無"
capture label variable KC_KOUSHINSU "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A1-4_契約更新回数"
capture label variable KC_SOSHIKI "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A2(1)_経営組織"
capture label variable KC_SANGYO "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A2(2)(3)_産業"
capture label variable KC_SYOKUGYO "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A3_職業"
capture label variable KC_KIBO "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A4_従業者規模"
capture label variable KC_SGNISSU "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A5(1)_年間日数"
capture label variable KC_SGKISOKU "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A5(2)_規則性"
capture label variable KC_SGJIKAN "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A5(3)_週時間"
capture label variable KC_SYOTOKU "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A6_年間所得"
capture label variable KC_SGGENGO "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A7_就業開始時期(元号)"
capture label variable KC_SGNEN "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A7_就業開始時期(年)"
capture label variable KC_SGTUKI "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A7_就業開始時期(月)"
capture label variable KC_KEIZOKU "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A8_継続希望"
capture label variable KC_KBRIYU "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A8-2_転職希望理由"
capture label variable KC_KBKEITAI "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A8-3_希望する仕事の形態"
capture label variable KC_KYUSYOKU "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A8-4_求職活動"
capture label variable KC_KBJIKAN "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A9_時間希望"
capture label variable KC_FKKBN "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A10_副業(有無・従業上の地位)"
capture label variable KC_FKSANGYO "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A11_副業の産業"
capture label variable KC_ZENSYUGYO "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A12_1年前の就業状態"
capture label variable KC_ZENUMU "オリジナル情報(最終チェック済データ)個人事項A_ふだん仕事をしている人: A13_前職の有無"
capture label variable KC_BKBUMU "オリジナル情報(最終チェック済データ)個人事項B_ふだん仕事をしていない人: B1_就業希望の有無"
capture label variable KC_BKBRIYU "オリジナル情報(最終チェック済データ)個人事項B_ふだん仕事をしていない人: B2_就業希望の理由"
capture label variable KC_BKBSYURUI "オリジナル情報(最終チェック済データ)個人事項B_ふだん仕事をしていない人: B3_希望する仕事の種類"
capture label variable KC_BKBKEITAI "オリジナル情報(最終チェック済データ)個人事項B_ふだん仕事をしていない人: B4_希望する仕事の形態"
capture label variable KC_BKYUSYOKU "オリジナル情報(最終チェック済データ)個人事項B_ふだん仕事をしていない人: B5_求職活動"
capture label variable KC_BRIYU "オリジナル情報(最終チェック済データ)個人事項B_ふだん仕事をしていない人: B6_非求職の理由"
capture label variable KC_BKBN "オリジナル情報(最終チェック済データ)個人事項B_ふだん仕事をしていない人: B7_求職期間(区分)"
capture label variable KC_BNEN "オリジナル情報(最終チェック済データ)個人事項B_ふだん仕事をしていない人: B7_求職期間(年)"
capture label variable KC_BTUKI "オリジナル情報(最終チェック済データ)個人事項B_ふだん仕事をしていない人: B7_求職期間(月)"
capture label variable KC_BKBJIKI "オリジナル情報(最終チェック済データ)個人事項B_ふだん仕事をしていない人: B8_就業希望時期"
capture label variable KC_BHKBRIYU "オリジナル情報(最終チェック済データ)個人事項B_ふだん仕事をしていない人: B9_就業非希望理由"
capture label variable KC_BZENSYUGYO "オリジナル情報(最終チェック済データ)個人事項B_ふだん仕事をしていない人: B10_1年前の就業状態"
capture label variable KC_BZENUMU "オリジナル情報(最終チェック済データ)個人事項B_ふだん仕事をしていない人: B11_前職の有無"
capture label variable KC_RSJIKI "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C1_離職時期(区分)"
capture label variable KC_RSGENGO "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C1_離職時期(元号)"
capture label variable KC_RSNEN "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C1_離職時期((年)"
capture label variable KC_RSTUKI "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C1_離職時期(月)"
capture label variable KC_RSKIKAN "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C2_就業期間(区分)"
capture label variable KC_RSKNEN "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C2_就業期間(年)"
capture label variable KC_RSKTUKI "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C2_就業期間(月)"
capture label variable KC_RSRIYU "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C3_離職理由"
capture label variable KC_RSCHII "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C4_従業上の地位"
capture label variable KC_RSSANGYO "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C5_産業(前職)"
capture label variable KC_RSSYOKUGYO "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C6_職業(前職)"
capture label variable KC_SSKBN "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C7_初職と現職・前職との関係"
capture label variable KC_SSGENGO "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C8_初職時期(元号)"
capture label variable KC_SSNEN "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C8_初職時期(年)"
capture label variable KC_SSTUKI "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C8_初職時期(月)"
capture label variable KC_SSCHIKEI "オリジナル情報(最終チェック済データ)個人事項C_前の仕事について: C9_初職の地位と形態"
capture label variable KC_EIKYO "オリジナル情報(最終チェック済データ)個人事項F_東日本大震災関連: F1_仕事への影響"
capture label variable KC_HINAN "オリジナル情報(最終チェック済データ)個人事項F_東日本大震災関連: F2_避難の有無"
capture label variable KC_HINANNOW "オリジナル情報(最終チェック済データ)個人事項F_東日本大震災関連: F2-2_避難状況"
capture label variable KC_SHINKBN "オリジナル情報(最終チェック済データ)個人事項F_東日本大震災関連: F2-3_震災時の居住地(区分)"
capture label variable KC_SHINKENCITY "オリジナル情報(最終チェック済データ)個人事項F_東日本大震災関連: F2-3_震災時の居住地"
capture label variable S_IPPAN "世帯に関する事項: 一般・単身世帯の別"
capture label variable S_KAZOKURUI12 "世帯に関する事項家族類型: 特定家族類型12区分"
capture label variable K_AGE "個人に関する事項年齢: 各歳"
capture label variable K_AGE5 "個人に関する事項年齢: 5歳階級"
capture label variable K_AGE10 "個人に関する事項年齢: 10歳階級"
