rename var0 H24年センサスKEY
rename var1 共通事業所コード
rename var2 民公区分
rename var3 経営組織
rename var4 本支区分
rename var5 常用労働者計LP事業所RP
rename var6 正社員LP事業所RP
rename var7 臨時雇用者LP事業所RP
rename var8 事業所産業分類LP大RP
rename var9 事業所産業分類LP中RP
rename var10 事業所産業分類LP小RP
rename var11 事業所開設時期
rename var12 共通企業コード
rename var13 常用雇用者計LP企業RP
rename var14 支所有無LP企業RP
rename var15 企業グループコード
rename var16 企業G階層
rename var17 親の有無
rename var18 子の有無
rename var19 トップ層
rename var20 ブランク0
rename var21 市外局番
rename var22 市内局番
rename var23 加入者番号
rename var24 郵便番号LP親RP
rename var25 郵便番号LP子RP
rename var26 事業所名称
rename var27 都道府県コード
rename var28 市区町村コード
rename var29 都道府県名
rename var30 市区町村名
rename var31 町丁字名等
rename var32 ビル名等
rename var33 監督署
rename var34 表示産業
rename var35 抽出単位産業
rename var36 企業規模
rename var37 事業所規模
rename var38 抽出事業所規模
rename var39 臨雇数規模
rename var40 事業所抽出間隔
rename var41 前年調査不能事由コード
rename var42 前年調査はがき削除フラグ
rename var43 使用不能事業所フラグ
rename var44 前年調査反映フラグ
rename var45 年次F変更把握フラグ
rename var46 サンプルマーク22
rename var47 サンプルマーク23
rename var48 サンプルマーク24
rename var49 サンプルマーク25
rename var50 サンプルマーク26
rename var51 サンプルマーク27
rename var52 サンプルマーク28
rename var53 重複是正対象フラグ
rename var54 ブランク1
rename var55 抽出率の分母LP常用雇用者数RP
rename var56 抽出率の分母LP臨時雇用者数RP
rename var57 個人票枚数
rename var58 調査一連番号
rename var59 チェックデジット
rename var60 抽出基本表集計用コード都道府県LP1RP
rename var61 抽出基本表集計用コード都道府県LP2RP
rename var62 抽出基本表集計用コード民公LP1RP
rename var63 抽出基本表集計用コード民公LP2RP
rename var64 抽出基本表集計用コード産業LP1RP
rename var65 抽出基本表集計用コード産業LP2RP
rename var66 抽出基本表集計用コード産業LP3RP
rename var67 抽出基本表集計用コード事業所規模LP1RP
rename var68 抽出基本表集計用コード事業所規模LP2RP
rename var69 抽出基本表集計用コード事業所規模LP3RP
rename var70 日本郵政
rename var71 造幣印刷
rename var72 JRNTT
rename var73 国立大学法人
rename var74 予備1
rename var75 予備2
rename var76 前年調査一連番号
rename var77 前年チェックデジット
rename var78 一括対応フラグ
rename var79 本社等一括番号
rename var80 桁あふれフラグ
rename var81 毎勤対象コード
