rename var0 センサスKEYLP県RP
rename var1 センサスKEYLP市区町村RP
rename var2 センサスKEYLP調査区RP
rename var3 センサスKEYLP事業所番号RP
rename var4 民公2LPKEYRP
rename var5 規模2LPKEYRP
rename var6 経営組織
rename var7 本支
rename var8 産業分類LP大RP
rename var9 産業分類LP中小RP
rename var10 産業分類LP細RP
rename var11 常用雇用者数
rename var12 臨時雇用者数
rename var13 企業の常用雇用者数LP国内RP
rename var14 種類LP民公RP
rename var15 省庁団体
rename var16 事業所の名称
rename var17 市外局番
rename var18 市内局番
rename var19 加入者番号
rename var20 郵便番号LP主RP
rename var21 郵便番号LP子RP
rename var22 都道府県コード
rename var23 市区町村コード
rename var24 都道府県名
rename var25 市区町村名
rename var26 町丁
rename var27 ビル名
rename var28 監督署
rename var29 表示産業
rename var30 抽出単位産業
rename var31 企業規模
rename var32 事業所規模
rename var33 抽出事業所規模
rename var34 臨雇数規模
rename var35 事業所抽出間隔
rename var36 サンプルマークLP22RP
rename var37 サンプルマークLP23RP
rename var38 サンプルマークLP24RP
rename var39 サンプルマークLP25RP
rename var40 サンプルマークLP26RP
rename var41 サンプルマークLP27RP
rename var42 是正・全数
rename var43 抽出率の分母LP常雇RP
rename var44 抽出率の分母LP臨雇RP
rename var45 個人票枚数
rename var46 調査一連番号
rename var47 チェックディジット
rename var48 旧KEYLP県RP
rename var49 旧KEYLP市区町村RP
rename var50 旧KEYLP調査区RP
rename var51 旧KEYLP事業所番号RP
rename var52 民公2LP旧KEYRP
rename var53 種類2LP旧KEYRP
rename var54 基本表集計用LP都道府県1RP
rename var55 基本表集計用LP都道府県2RP
rename var56 基本表集計用LP民公1RP
rename var57 基本表集計用LP民公2RP
rename var58 基本表集計用LP産業1RP
rename var59 基本表集計用LP産業2RP
rename var60 基本表集計用LP産業3RP
rename var61 基本表集計用LP事業所規模1RP
rename var62 基本表集計用LP事業所規模2RP
rename var63 基本表集計用LP事業所規模3RP
rename var64 日本郵政
rename var65 造幣・印刷局
rename var66 JRNTT
rename var67 国立大学法人
rename var68 共通事業所コード
rename var69 町丁・大字コード
rename var70 直轄企業コードLP県RP
rename var71 直轄企業コードLP市区町村RP
rename var72 直轄企業コードLP調査区RP
rename var73 直轄企業コードLP事業所番号RP
