/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2020/08/22 18:11:16
-----------------------------------------------------------------------------*/


/*----------------------------------------------------------------------
    Description (Base):    "M/C"
    Description (Data 1):  "M/C"
    Description (Data 2):  "M/C"
    Description (Data 3):  "M/C"
    Description (Data 4):  "M/C"
    Description (Data 5):  "M/C"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v1_NEWVARIABLE = "."
capture replace v1_NEWVARIABLE = var1  if flag_tmp_NEWVARIABLE==1
capture replace v1_NEWVARIABLE = var1  if flag_tmp_NEWVARIABLE==2
capture replace v1_NEWVARIABLE = var1  if flag_tmp_NEWVARIABLE==3
capture replace v1_NEWVARIABLE = var1  if flag_tmp_NEWVARIABLE==4
capture replace v1_NEWVARIABLE = var1  if flag_tmp_NEWVARIABLE==5
capture label variable v1_NEWVARIABLE "M/C"


/*----------------------------------------------------------------------
    Description (Base):    "識別符号"
    Description (Data 1):  "識別符号"
    Description (Data 2):  "識別符号"
    Description (Data 3):  "識別符号"
    Description (Data 4):  "識別符号"
    Description (Data 5):  "識別符号"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v2_NEWVARIABLE = "."
capture replace v2_NEWVARIABLE = var2  if flag_tmp_NEWVARIABLE==1
capture replace v2_NEWVARIABLE = var2  if flag_tmp_NEWVARIABLE==2
capture replace v2_NEWVARIABLE = var2  if flag_tmp_NEWVARIABLE==3
capture replace v2_NEWVARIABLE = var2  if flag_tmp_NEWVARIABLE==4
capture replace v2_NEWVARIABLE = var2  if flag_tmp_NEWVARIABLE==5
capture label variable v2_NEWVARIABLE "識別符号"


/*----------------------------------------------------------------------
    Description (Base):    "KEY1: 括番"
    Description (Data 1):  "KEY1: 括番"
    Description (Data 2):  "KEY1: 括番"
    Description (Data 3):  "KEY1: 括番"
    Description (Data 4):  "KEY1: 括番"
    Description (Data 5):  "KEY1: 括番"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v3_NEWVARIABLE = "."
capture replace v3_NEWVARIABLE = var3  if flag_tmp_NEWVARIABLE==1
capture replace v3_NEWVARIABLE = var3  if flag_tmp_NEWVARIABLE==2
capture replace v3_NEWVARIABLE = var3  if flag_tmp_NEWVARIABLE==3
capture replace v3_NEWVARIABLE = var3  if flag_tmp_NEWVARIABLE==4
capture replace v3_NEWVARIABLE = var3  if flag_tmp_NEWVARIABLE==5
capture label variable v3_NEWVARIABLE "KEY1: 括番"


/*----------------------------------------------------------------------
    Description (Base):    "KEY1: 通し番号"
    Description (Data 1):  "KEY1: 通し番号"
    Description (Data 2):  "KEY1: 通し番号"
    Description (Data 3):  "KEY1: 通し番号"
    Description (Data 4):  "KEY1: 通し番号"
    Description (Data 5):  "KEY1: 通し番号"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v4_NEWVARIABLE = "."
capture replace v4_NEWVARIABLE = var4  if flag_tmp_NEWVARIABLE==1
capture replace v4_NEWVARIABLE = var4  if flag_tmp_NEWVARIABLE==2
capture replace v4_NEWVARIABLE = var4  if flag_tmp_NEWVARIABLE==3
capture replace v4_NEWVARIABLE = var4  if flag_tmp_NEWVARIABLE==4
capture replace v4_NEWVARIABLE = var4  if flag_tmp_NEWVARIABLE==5
capture label variable v4_NEWVARIABLE "KEY1: 通し番号"


/*----------------------------------------------------------------------
    Description (Base):    "KEY: 府県"
    Description (Data 1):  "KEY: 府県"
    Description (Data 2):  "KEY: 府県"
    Description (Data 3):  "KEY: 府県"
    Description (Data 4):  "KEY: 府県"
    Description (Data 5):  "KEY: 府県"

    Values (Base):     1: 北海道, 2: 青森, 3: 岩手, 4: 宮城, 5: 秋田, 6: 山形, 7: 福島, 8: 茨城, 9: 栃木, 10: 群馬, 11: 埼玉, 12: 千葉, 13: 東京, 14: 神奈川, 15: 新潟, 16: 富山, 17: 石川, 18: 福井, 19: 山梨, 20: 長野, 21: 岐阜, 22: 静岡, 23: 愛知, 24: 三重, 25: 滋賀, 26: 京都, 27: 大阪, 28: 兵庫, 29: 奈良, 30: 和歌山, 31: 鳥取, 32: 島根, 33: 岡山, 34: 広島, 35: 山口, 36: 徳島, 37: 香川, 38: 愛媛, 39: 高知, 40: 福岡, 41: 佐賀, 42: 長崎, 43: 熊本, 44: 大分, 45: 宮崎, 46: 鹿児島, 47: 沖縄
    Values (Data 1):   1: 北海道, 2: 青森, 3: 岩手, 4: 宮城, 5: 秋田, 6: 山形, 7: 福島, 8: 茨城, 9: 栃木, 10: 群馬, 11: 埼玉, 12: 千葉, 13: 東京, 14: 神奈川, 15: 新潟, 16: 富山, 17: 石川, 18: 福井, 19: 山梨, 20: 長野, 21: 岐阜, 22: 静岡, 23: 愛知, 24: 三重, 25: 滋賀, 26: 京都, 27: 大阪, 28: 兵庫, 29: 奈良, 30: 和歌山, 31: 鳥取, 32: 島根, 33: 岡山, 34: 広島, 35: 山口, 36: 徳島, 37: 香川, 38: 愛媛, 39: 高知, 40: 福岡, 41: 佐賀, 42: 長崎, 43: 熊本, 44: 大分, 45: 宮崎, 46: 鹿児島, 47: 沖縄
    Values (Data 2):   1: 北海道, 2: 青森, 3: 岩手, 4: 宮城, 5: 秋田, 6: 山形, 7: 福島, 8: 茨城, 9: 栃木, 10: 群馬, 11: 埼玉, 12: 千葉, 13: 東京, 14: 神奈川, 15: 新潟, 16: 富山, 17: 石川, 18: 福井, 19: 山梨, 20: 長野, 21: 岐阜, 22: 静岡, 23: 愛知, 24: 三重, 25: 滋賀, 26: 京都, 27: 大阪, 28: 兵庫, 29: 奈良, 30: 和歌山, 31: 鳥取, 32: 島根, 33: 岡山, 34: 広島, 35: 山口, 36: 徳島, 37: 香川, 38: 愛媛, 39: 高知, 40: 福岡, 41: 佐賀, 42: 長崎, 43: 熊本, 44: 大分, 45: 宮崎, 46: 鹿児島, 47: 沖縄
    Values (Data 3):   1: 北海道, 2: 青森, 3: 岩手, 4: 宮城, 5: 秋田, 6: 山形, 7: 福島, 8: 茨城, 9: 栃木, 10: 群馬, 11: 埼玉, 12: 千葉, 13: 東京, 14: 神奈川, 15: 新潟, 16: 富山, 17: 石川, 18: 福井, 19: 山梨, 20: 長野, 21: 岐阜, 22: 静岡, 23: 愛知, 24: 三重, 25: 滋賀, 26: 京都, 27: 大阪, 28: 兵庫, 29: 奈良, 30: 和歌山, 31: 鳥取, 32: 島根, 33: 岡山, 34: 広島, 35: 山口, 36: 徳島, 37: 香川, 38: 愛媛, 39: 高知, 40: 福岡, 41: 佐賀, 42: 長崎, 43: 熊本, 44: 大分, 45: 宮崎, 46: 鹿児島, 47: 沖縄
    Values (Data 4):   1: 北海道, 2: 青森, 3: 岩手, 4: 宮城, 5: 秋田, 6: 山形, 7: 福島, 8: 茨城, 9: 栃木, 10: 群馬, 11: 埼玉, 12: 千葉, 13: 東京, 14: 神奈川, 15: 新潟, 16: 富山, 17: 石川, 18: 福井, 19: 山梨, 20: 長野, 21: 岐阜, 22: 静岡, 23: 愛知, 24: 三重, 25: 滋賀, 26: 京都, 27: 大阪, 28: 兵庫, 29: 奈良, 30: 和歌山, 31: 鳥取, 32: 島根, 33: 岡山, 34: 広島, 35: 山口, 36: 徳島, 37: 香川, 38: 愛媛, 39: 高知, 40: 福岡, 41: 佐賀, 42: 長崎, 43: 熊本, 44: 大分, 45: 宮崎, 46: 鹿児島, 47: 沖縄
    Values (Data 5):   1: 北海道, 2: 青森, 3: 岩手, 4: 宮城, 5: 秋田, 6: 山形, 7: 福島, 8: 茨城, 9: 栃木, 10: 群馬, 11: 埼玉, 12: 千葉, 13: 東京, 14: 神奈川, 15: 新潟, 16: 富山, 17: 石川, 18: 福井, 19: 山梨, 20: 長野, 21: 岐阜, 22: 静岡, 23: 愛知, 24: 三重, 25: 滋賀, 26: 京都, 27: 大阪, 28: 兵庫, 29: 奈良, 30: 和歌山, 31: 鳥取, 32: 島根, 33: 岡山, 34: 広島, 35: 山口, 36: 徳島, 37: 香川, 38: 愛媛, 39: 高知, 40: 福岡, 41: 佐賀, 42: 長崎, 43: 熊本, 44: 大分, 45: 宮崎, 46: 鹿児島, 47: 沖縄

----------------------------------------------------------------------*/
gen v5_NEWVARIABLE = "."
capture replace v5_NEWVARIABLE = var5  if flag_tmp_NEWVARIABLE==1
capture replace v5_NEWVARIABLE = var5  if flag_tmp_NEWVARIABLE==2
capture replace v5_NEWVARIABLE = var5  if flag_tmp_NEWVARIABLE==3
capture replace v5_NEWVARIABLE = var5  if flag_tmp_NEWVARIABLE==4
capture replace v5_NEWVARIABLE = var5  if flag_tmp_NEWVARIABLE==5
capture label variable v5_NEWVARIABLE "KEY: 府県"


/*----------------------------------------------------------------------
    Description (Base):    "KEY: 調査区"
    Description (Data 1):  "KEY: 調査区"
    Description (Data 2):  "KEY: 調査区"
    Description (Data 3):  "KEY: 調査区"
    Description (Data 4):  "KEY: 調査区"
    Description (Data 5):  "KEY: 調査区"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v6_NEWVARIABLE = "."
capture replace v6_NEWVARIABLE = var6  if flag_tmp_NEWVARIABLE==1
capture replace v6_NEWVARIABLE = var6  if flag_tmp_NEWVARIABLE==2
capture replace v6_NEWVARIABLE = var6  if flag_tmp_NEWVARIABLE==3
capture replace v6_NEWVARIABLE = var6  if flag_tmp_NEWVARIABLE==4
capture replace v6_NEWVARIABLE = var6  if flag_tmp_NEWVARIABLE==5
capture label variable v6_NEWVARIABLE "KEY: 調査区"


/*----------------------------------------------------------------------
    Description (Base):    "KEY: 事業所一連・調査区内一連"
    Description (Data 1):  "KEY: 事業所一連・調査区内一連"
    Description (Data 2):  "KEY: 事業所一連・調査区内一連"
    Description (Data 3):  "KEY: 事業所一連・調査区内一連"
    Description (Data 4):  "KEY: 事業所一連・調査区内一連"
    Description (Data 5):  "KEY: 事業所一連・調査区内一連"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v7_NEWVARIABLE = "."
capture replace v7_NEWVARIABLE = var7  if flag_tmp_NEWVARIABLE==1
capture replace v7_NEWVARIABLE = var7  if flag_tmp_NEWVARIABLE==2
capture replace v7_NEWVARIABLE = var7  if flag_tmp_NEWVARIABLE==3
capture replace v7_NEWVARIABLE = var7  if flag_tmp_NEWVARIABLE==4
capture replace v7_NEWVARIABLE = var7  if flag_tmp_NEWVARIABLE==5
capture label variable v7_NEWVARIABLE "KEY: 事業所一連・調査区内一連"


/*----------------------------------------------------------------------
    Description (Base):    "KEY: 重複KEY"
    Description (Data 1):  "KEY: 重複KEY"
    Description (Data 2):  "KEY: 重複KEY"
    Description (Data 3):  "KEY: 重複KEY"
    Description (Data 4):  "KEY: 重複KEY"
    Description (Data 5):  "KEY: 重複KEY"

    Values (Base):     0: 重複なし
    Values (Data 1):   0: 重複なし
    Values (Data 2):   0: 重複なし
    Values (Data 3):   0: 重複なし
    Values (Data 4):   0: 重複なし
    Values (Data 5):   0: 重複なし

----------------------------------------------------------------------*/
gen v8_NEWVARIABLE = "."
capture replace v8_NEWVARIABLE = var8  if flag_tmp_NEWVARIABLE==1
capture replace v8_NEWVARIABLE = var8  if flag_tmp_NEWVARIABLE==2
capture replace v8_NEWVARIABLE = var8  if flag_tmp_NEWVARIABLE==3
capture replace v8_NEWVARIABLE = var8  if flag_tmp_NEWVARIABLE==4
capture replace v8_NEWVARIABLE = var8  if flag_tmp_NEWVARIABLE==5
capture label variable v8_NEWVARIABLE "KEY: 重複KEY"


/*----------------------------------------------------------------------
    Description (Base):    "抽出符号"
    Description (Data 1):  "抽出符号"
    Description (Data 2):  "抽出符号"
    Description (Data 3):  "抽出符号"
    Description (Data 4):  "抽出符号"
    Description (Data 5):  "抽出符号"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v9_NEWVARIABLE = "."
capture replace v9_NEWVARIABLE = var9  if flag_tmp_NEWVARIABLE==1
capture replace v9_NEWVARIABLE = var9  if flag_tmp_NEWVARIABLE==2
capture replace v9_NEWVARIABLE = var9  if flag_tmp_NEWVARIABLE==3
capture replace v9_NEWVARIABLE = var9  if flag_tmp_NEWVARIABLE==4
capture replace v9_NEWVARIABLE = var9  if flag_tmp_NEWVARIABLE==5
capture label variable v9_NEWVARIABLE "抽出符号"


/*----------------------------------------------------------------------
    Description (Base):    "産業: 標準産業"
    Description (Data 1):  "産業: 標準産業"
    Description (Data 2):  "産業: 標準産業"
    Description (Data 3):  "産業: 標準産業"
    Description (Data 4):  "産業: 標準産業"
    Description (Data 5):  "産業: 標準産業"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v10_NEWVARIABLE = "."
capture replace v10_NEWVARIABLE = var10  if flag_tmp_NEWVARIABLE==1
capture replace v10_NEWVARIABLE = var10  if flag_tmp_NEWVARIABLE==2
capture replace v10_NEWVARIABLE = var10  if flag_tmp_NEWVARIABLE==3
capture replace v10_NEWVARIABLE = var10  if flag_tmp_NEWVARIABLE==4
capture replace v10_NEWVARIABLE = var10  if flag_tmp_NEWVARIABLE==5
capture label variable v10_NEWVARIABLE "産業: 標準産業"


/*----------------------------------------------------------------------
    Description (Base):    "産業集計産業コード: 大中分類"
    Description (Data 1):  "産業集計産業コード: 大中分類"
    Description (Data 2):  "産業集計産業コード: 大中分類"
    Description (Data 3):  "産業集計産業コード: 大中分類"
    Description (Data 4):  "産業集計産業コード: 大中分類"
    Description (Data 5):  "産業集計産業コード: 大中分類"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v11_NEWVARIABLE = "."
capture replace v11_NEWVARIABLE = var11  if flag_tmp_NEWVARIABLE==1
capture replace v11_NEWVARIABLE = var11  if flag_tmp_NEWVARIABLE==2
capture replace v11_NEWVARIABLE = var11  if flag_tmp_NEWVARIABLE==3
capture replace v11_NEWVARIABLE = var11  if flag_tmp_NEWVARIABLE==4
capture replace v11_NEWVARIABLE = var11  if flag_tmp_NEWVARIABLE==5
capture label variable v11_NEWVARIABLE "産業集計産業コード: 大中分類"


/*----------------------------------------------------------------------
    Description (Base):    "産業集計産業コード: 特掲産業1"
    Description (Data 1):  "産業集計産業コード: 特掲産業1"
    Description (Data 2):  "産業集計産業コード: 特掲産業1"
    Description (Data 3):  "産業集計産業コード: 特掲産業1"
    Description (Data 4):  "産業集計産業コード: 特掲産業1"
    Description (Data 5):  "産業集計産業コード: 特掲産業1"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v12_NEWVARIABLE = "."
capture replace v12_NEWVARIABLE = var12  if flag_tmp_NEWVARIABLE==1
capture replace v12_NEWVARIABLE = var12  if flag_tmp_NEWVARIABLE==2
capture replace v12_NEWVARIABLE = var12  if flag_tmp_NEWVARIABLE==3
capture replace v12_NEWVARIABLE = var12  if flag_tmp_NEWVARIABLE==4
capture replace v12_NEWVARIABLE = var12  if flag_tmp_NEWVARIABLE==5
capture label variable v12_NEWVARIABLE "産業集計産業コード: 特掲産業1"


/*----------------------------------------------------------------------
    Description (Base):    "産業集計産業コード: 特掲産業2"
    Description (Data 1):  "産業集計産業コード: 特掲産業2"
    Description (Data 2):  "産業集計産業コード: 特掲産業2"
    Description (Data 3):  "産業集計産業コード: 特掲産業2"
    Description (Data 4):  "産業集計産業コード: 特掲産業2"
    Description (Data 5):  "産業集計産業コード: 特掲産業2"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v13_NEWVARIABLE = "."
capture replace v13_NEWVARIABLE = var13  if flag_tmp_NEWVARIABLE==1
capture replace v13_NEWVARIABLE = var13  if flag_tmp_NEWVARIABLE==2
capture replace v13_NEWVARIABLE = var13  if flag_tmp_NEWVARIABLE==3
capture replace v13_NEWVARIABLE = var13  if flag_tmp_NEWVARIABLE==4
capture replace v13_NEWVARIABLE = var13  if flag_tmp_NEWVARIABLE==5
capture label variable v13_NEWVARIABLE "産業集計産業コード: 特掲産業2"


/*----------------------------------------------------------------------
    Description (Base):    "事業所規模"
    Description (Data 1):  "事業所規模"
    Description (Data 2):  "事業所規模"
    Description (Data 3):  "事業所規模"
    Description (Data 4):  "事業所規模"
    Description (Data 5):  "事業所規模"

    Values (Base):     1: 1,000人以上, 3: 500~999人, 5: 100~499人, 7: 30~99人, 9: 5~29人
    Values (Data 1):   1: 1,000人以上, 3: 500~999人, 5: 100~499人, 7: 30~99人, 9: 5~29人
    Values (Data 2):   1: 1,000人以上, 3: 500~999人, 5: 100~499人, 7: 30~99人, 9: 5~29人
    Values (Data 3):   1: 1,000人以上, 3: 500~999人, 5: 100~499人, 7: 30~99人, 9: 5~29人
    Values (Data 4):   1: 1,000人以上, 3: 500~999人, 5: 100~499人, 7: 30~99人, 9: 5~29人
    Values (Data 5):   1: 1,000人以上, 3: 500~999人, 5: 100~499人, 7: 30~99人, 9: 5~29人

----------------------------------------------------------------------*/
gen v14_NEWVARIABLE = "."
capture replace v14_NEWVARIABLE = var14  if flag_tmp_NEWVARIABLE==1
capture replace v14_NEWVARIABLE = var14  if flag_tmp_NEWVARIABLE==2
capture replace v14_NEWVARIABLE = var14  if flag_tmp_NEWVARIABLE==3
capture replace v14_NEWVARIABLE = var14  if flag_tmp_NEWVARIABLE==4
capture replace v14_NEWVARIABLE = var14  if flag_tmp_NEWVARIABLE==5
capture label variable v14_NEWVARIABLE "事業所規模"


/*----------------------------------------------------------------------
    Description (Base):    "企業規模"
    Description (Data 1):  "企業規模"
    Description (Data 2):  "企業規模"
    Description (Data 3):  "企業規模"
    Description (Data 4):  "企業規模"
    Description (Data 5):  "企業規模"

    Values (Base):     1: 1,000人以上, 2: 500~999人, 3: 100~499人, 4: 30~99人, 5: 5~29人
    Values (Data 1):   1: 1,000人以上, 2: 500~999人, 3: 100~499人, 4: 30~99人, 5: 5~29人
    Values (Data 2):   1: 1,000人以上, 2: 500~999人, 3: 100~499人, 4: 30~99人, 5: 5~29人
    Values (Data 3):   1: 1,000人以上, 2: 500~999人, 3: 100~499人, 4: 30~99人, 5: 5~29人
    Values (Data 4):   1: 1,000人以上, 2: 500~999人, 3: 100~499人, 4: 30~99人, 5: 5~29人
    Values (Data 5):   1: 1,000人以上, 2: 500~999人, 3: 100~499人, 4: 30~99人, 5: 5~29人

----------------------------------------------------------------------*/
gen v15_NEWVARIABLE = "."
capture replace v15_NEWVARIABLE = var15  if flag_tmp_NEWVARIABLE==1
capture replace v15_NEWVARIABLE = var15  if flag_tmp_NEWVARIABLE==2
capture replace v15_NEWVARIABLE = var15  if flag_tmp_NEWVARIABLE==3
capture replace v15_NEWVARIABLE = var15  if flag_tmp_NEWVARIABLE==4
capture replace v15_NEWVARIABLE = var15  if flag_tmp_NEWVARIABLE==5
capture label variable v15_NEWVARIABLE "企業規模"


/*----------------------------------------------------------------------
    Description (Base):    "調査年月: 年"
    Description (Data 1):  "調査年月: 年"
    Description (Data 2):  "調査年月: 年"
    Description (Data 3):  "調査年月: 年"
    Description (Data 4):  "調査年月: 年"
    Description (Data 5):  "調査年月: 年"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v16_NEWVARIABLE = "."
capture replace v16_NEWVARIABLE = var16  if flag_tmp_NEWVARIABLE==1
capture replace v16_NEWVARIABLE = var16  if flag_tmp_NEWVARIABLE==2
capture replace v16_NEWVARIABLE = var16  if flag_tmp_NEWVARIABLE==3
capture replace v16_NEWVARIABLE = var16  if flag_tmp_NEWVARIABLE==4
capture replace v16_NEWVARIABLE = var16  if flag_tmp_NEWVARIABLE==5
capture label variable v16_NEWVARIABLE "調査年月: 年"


/*----------------------------------------------------------------------
    Description (Base):    "調査年月: 月"
    Description (Data 1):  "調査年月: 月"
    Description (Data 2):  "調査年月: 月"
    Description (Data 3):  "調査年月: 月"
    Description (Data 4):  "調査年月: 月"
    Description (Data 5):  "調査年月: 月"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v17_NEWVARIABLE = "."
capture replace v17_NEWVARIABLE = var17  if flag_tmp_NEWVARIABLE==1
capture replace v17_NEWVARIABLE = var17  if flag_tmp_NEWVARIABLE==2
capture replace v17_NEWVARIABLE = var17  if flag_tmp_NEWVARIABLE==3
capture replace v17_NEWVARIABLE = var17  if flag_tmp_NEWVARIABLE==4
capture replace v17_NEWVARIABLE = var17  if flag_tmp_NEWVARIABLE==5
capture label variable v17_NEWVARIABLE "調査年月: 月"


/*----------------------------------------------------------------------
    Description (Base):    "事業所照合"
    Description (Data 1):  "事業所照合"
    Description (Data 2):  "事業所照合"
    Description (Data 3):  "事業所照合"
    Description (Data 4):  "事業所照合"
    Description (Data 5):  "事業所照合"

    Values (Base):     1: 照合済
    Values (Data 1):   1: 照合済
    Values (Data 2):   1: 照合済
    Values (Data 3):   1: 照合済
    Values (Data 4):   1: 照合済
    Values (Data 5):   1: 照合済

----------------------------------------------------------------------*/
gen v18_NEWVARIABLE = "."
capture replace v18_NEWVARIABLE = var18  if flag_tmp_NEWVARIABLE==1
capture replace v18_NEWVARIABLE = var18  if flag_tmp_NEWVARIABLE==2
capture replace v18_NEWVARIABLE = var18  if flag_tmp_NEWVARIABLE==3
capture replace v18_NEWVARIABLE = var18  if flag_tmp_NEWVARIABLE==4
capture replace v18_NEWVARIABLE = var18  if flag_tmp_NEWVARIABLE==5
capture label variable v18_NEWVARIABLE "事業所照合"


/*----------------------------------------------------------------------
    Description (Base):    "内検ランク"
    Description (Data 1):  "内検ランク"
    Description (Data 2):  "内検ランク"
    Description (Data 3):  "内検ランク"
    Description (Data 4):  "内検ランク"
    Description (Data 5):  "内検ランク"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v19_NEWVARIABLE = "."
capture replace v19_NEWVARIABLE = var19  if flag_tmp_NEWVARIABLE==1
capture replace v19_NEWVARIABLE = var19  if flag_tmp_NEWVARIABLE==2
capture replace v19_NEWVARIABLE = var19  if flag_tmp_NEWVARIABLE==3
capture replace v19_NEWVARIABLE = var19  if flag_tmp_NEWVARIABLE==4
capture replace v19_NEWVARIABLE = var19  if flag_tmp_NEWVARIABLE==5
capture label variable v19_NEWVARIABLE "内検ランク"


/*----------------------------------------------------------------------
    Description (Base):    "区分1(男)常用労働者数: 前月末"
    Description (Data 1):  "区分1(男)常用労働者数: 前月末"
    Description (Data 2):  "区分1(男)常用労働者数: 前月末"
    Description (Data 3):  "区分1(男)常用労働者数: 前月末"
    Description (Data 4):  "区分1(男)常用労働者数: 前月末"
    Description (Data 5):  "区分1(男)常用労働者数: 前月末"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v20_NEWVARIABLE = "."
capture replace v20_NEWVARIABLE = var20  if flag_tmp_NEWVARIABLE==1
capture replace v20_NEWVARIABLE = var20  if flag_tmp_NEWVARIABLE==2
capture replace v20_NEWVARIABLE = var20  if flag_tmp_NEWVARIABLE==3
capture replace v20_NEWVARIABLE = var20  if flag_tmp_NEWVARIABLE==4
capture replace v20_NEWVARIABLE = var20  if flag_tmp_NEWVARIABLE==5
capture label variable v20_NEWVARIABLE "区分1(男)常用労働者数: 前月末"


/*----------------------------------------------------------------------
    Description (Base):    "区分1(男)常用労働者数: 増加"
    Description (Data 1):  "区分1(男)常用労働者数: 増加"
    Description (Data 2):  "区分1(男)常用労働者数: 増加"
    Description (Data 3):  "区分1(男)常用労働者数: 増加"
    Description (Data 4):  "区分1(男)常用労働者数: 増加"
    Description (Data 5):  "区分1(男)常用労働者数: 増加"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v21_NEWVARIABLE = "."
capture replace v21_NEWVARIABLE = var21  if flag_tmp_NEWVARIABLE==1
capture replace v21_NEWVARIABLE = var21  if flag_tmp_NEWVARIABLE==2
capture replace v21_NEWVARIABLE = var21  if flag_tmp_NEWVARIABLE==3
capture replace v21_NEWVARIABLE = var21  if flag_tmp_NEWVARIABLE==4
capture replace v21_NEWVARIABLE = var21  if flag_tmp_NEWVARIABLE==5
capture label variable v21_NEWVARIABLE "区分1(男)常用労働者数: 増加"


/*----------------------------------------------------------------------
    Description (Base):    "区分1(男)常用労働者数: 減少"
    Description (Data 1):  "区分1(男)常用労働者数: 減少"
    Description (Data 2):  "区分1(男)常用労働者数: 減少"
    Description (Data 3):  "区分1(男)常用労働者数: 減少"
    Description (Data 4):  "区分1(男)常用労働者数: 減少"
    Description (Data 5):  "区分1(男)常用労働者数: 減少"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v22_NEWVARIABLE = "."
capture replace v22_NEWVARIABLE = var22  if flag_tmp_NEWVARIABLE==1
capture replace v22_NEWVARIABLE = var22  if flag_tmp_NEWVARIABLE==2
capture replace v22_NEWVARIABLE = var22  if flag_tmp_NEWVARIABLE==3
capture replace v22_NEWVARIABLE = var22  if flag_tmp_NEWVARIABLE==4
capture replace v22_NEWVARIABLE = var22  if flag_tmp_NEWVARIABLE==5
capture label variable v22_NEWVARIABLE "区分1(男)常用労働者数: 減少"


/*----------------------------------------------------------------------
    Description (Base):    "区分1(男)常用労働者数: 本月末"
    Description (Data 1):  "区分1(男)常用労働者数: 本月末"
    Description (Data 2):  "区分1(男)常用労働者数: 本月末"
    Description (Data 3):  "区分1(男)常用労働者数: 本月末"
    Description (Data 4):  "区分1(男)常用労働者数: 本月末"
    Description (Data 5):  "区分1(男)常用労働者数: 本月末"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v23_NEWVARIABLE = "."
capture replace v23_NEWVARIABLE = var23  if flag_tmp_NEWVARIABLE==1
capture replace v23_NEWVARIABLE = var23  if flag_tmp_NEWVARIABLE==2
capture replace v23_NEWVARIABLE = var23  if flag_tmp_NEWVARIABLE==3
capture replace v23_NEWVARIABLE = var23  if flag_tmp_NEWVARIABLE==4
capture replace v23_NEWVARIABLE = var23  if flag_tmp_NEWVARIABLE==5
capture label variable v23_NEWVARIABLE "区分1(男)常用労働者数: 本月末"


/*----------------------------------------------------------------------
    Description (Base):    "区分1(男)常用労働者数: 本月末のうちパートタイム労働者"
    Description (Data 1):  "区分1(男)常用労働者数: 本月末のうちパートタイム労働者"
    Description (Data 2):  "区分1(男)常用労働者数: 本月末のうちパートタイム労働者"
    Description (Data 3):  "区分1(男)常用労働者数: 本月末のうちパートタイム労働者"
    Description (Data 4):  "区分1(男)常用労働者数: 本月末のうちパートタイム労働者"
    Description (Data 5):  "区分1(男)常用労働者数: 本月末のうちパートタイム労働者"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v24_NEWVARIABLE = "."
capture replace v24_NEWVARIABLE = var24  if flag_tmp_NEWVARIABLE==1
capture replace v24_NEWVARIABLE = var24  if flag_tmp_NEWVARIABLE==2
capture replace v24_NEWVARIABLE = var24  if flag_tmp_NEWVARIABLE==3
capture replace v24_NEWVARIABLE = var24  if flag_tmp_NEWVARIABLE==4
capture replace v24_NEWVARIABLE = var24  if flag_tmp_NEWVARIABLE==5
capture label variable v24_NEWVARIABLE "区分1(男)常用労働者数: 本月末のうちパートタイム労働者"


/*----------------------------------------------------------------------
    Description (Base):    "区分1(男): 出勤日数"
    Description (Data 1):  "区分1(男): 出勤日数"
    Description (Data 2):  "区分1(男): 出勤日数"
    Description (Data 3):  "区分1(男): 出勤日数"
    Description (Data 4):  "区分1(男): 出勤日数"
    Description (Data 5):  "区分1(男): 出勤日数"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v25_NEWVARIABLE = "."
capture replace v25_NEWVARIABLE = var25  if flag_tmp_NEWVARIABLE==1
capture replace v25_NEWVARIABLE = var25  if flag_tmp_NEWVARIABLE==2
capture replace v25_NEWVARIABLE = var25  if flag_tmp_NEWVARIABLE==3
capture replace v25_NEWVARIABLE = var25  if flag_tmp_NEWVARIABLE==4
capture replace v25_NEWVARIABLE = var25  if flag_tmp_NEWVARIABLE==5
capture label variable v25_NEWVARIABLE "区分1(男): 出勤日数"


/*----------------------------------------------------------------------
    Description (Base):    "区分1(男): 所定内労働時間"
    Description (Data 1):  "区分1(男): 所定内労働時間"
    Description (Data 2):  "区分1(男): 所定内労働時間"
    Description (Data 3):  "区分1(男): 所定内労働時間"
    Description (Data 4):  "区分1(男): 所定内労働時間"
    Description (Data 5):  "区分1(男): 所定内労働時間"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v26_NEWVARIABLE = "."
capture replace v26_NEWVARIABLE = var26  if flag_tmp_NEWVARIABLE==1
capture replace v26_NEWVARIABLE = var26  if flag_tmp_NEWVARIABLE==2
capture replace v26_NEWVARIABLE = var26  if flag_tmp_NEWVARIABLE==3
capture replace v26_NEWVARIABLE = var26  if flag_tmp_NEWVARIABLE==4
capture replace v26_NEWVARIABLE = var26  if flag_tmp_NEWVARIABLE==5
capture label variable v26_NEWVARIABLE "区分1(男): 所定内労働時間"


/*----------------------------------------------------------------------
    Description (Base):    "区分1(男): 所定外労働時間"
    Description (Data 1):  "区分1(男): 所定外労働時間"
    Description (Data 2):  "区分1(男): 所定外労働時間"
    Description (Data 3):  "区分1(男): 所定外労働時間"
    Description (Data 4):  "区分1(男): 所定外労働時間"
    Description (Data 5):  "区分1(男): 所定外労働時間"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v27_NEWVARIABLE = "."
capture replace v27_NEWVARIABLE = var27  if flag_tmp_NEWVARIABLE==1
capture replace v27_NEWVARIABLE = var27  if flag_tmp_NEWVARIABLE==2
capture replace v27_NEWVARIABLE = var27  if flag_tmp_NEWVARIABLE==3
capture replace v27_NEWVARIABLE = var27  if flag_tmp_NEWVARIABLE==4
capture replace v27_NEWVARIABLE = var27  if flag_tmp_NEWVARIABLE==5
capture label variable v27_NEWVARIABLE "区分1(男): 所定外労働時間"


/*----------------------------------------------------------------------
    Description (Base):    "区分1(男): きまって支給する現金給与額"
    Description (Data 1):  "区分1(男): きまって支給する現金給与額"
    Description (Data 2):  "区分1(男): きまって支給する現金給与額"
    Description (Data 3):  "区分1(男): きまって支給する現金給与額"
    Description (Data 4):  "区分1(男): きまって支給する現金給与額"
    Description (Data 5):  "区分1(男): きまって支給する現金給与額"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v28_NEWVARIABLE = "."
capture replace v28_NEWVARIABLE = var28  if flag_tmp_NEWVARIABLE==1
capture replace v28_NEWVARIABLE = var28  if flag_tmp_NEWVARIABLE==2
capture replace v28_NEWVARIABLE = var28  if flag_tmp_NEWVARIABLE==3
capture replace v28_NEWVARIABLE = var28  if flag_tmp_NEWVARIABLE==4
capture replace v28_NEWVARIABLE = var28  if flag_tmp_NEWVARIABLE==5
capture label variable v28_NEWVARIABLE "区分1(男): きまって支給する現金給与額"


/*----------------------------------------------------------------------
    Description (Base):    "区分1(男): 特別給与額"
    Description (Data 1):  "区分1(男): 特別給与額"
    Description (Data 2):  "区分1(男): 特別給与額"
    Description (Data 3):  "区分1(男): 特別給与額"
    Description (Data 4):  "区分1(男): 特別給与額"
    Description (Data 5):  "区分1(男): 特別給与額"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v29_NEWVARIABLE = "."
capture replace v29_NEWVARIABLE = var29  if flag_tmp_NEWVARIABLE==1
capture replace v29_NEWVARIABLE = var29  if flag_tmp_NEWVARIABLE==2
capture replace v29_NEWVARIABLE = var29  if flag_tmp_NEWVARIABLE==3
capture replace v29_NEWVARIABLE = var29  if flag_tmp_NEWVARIABLE==4
capture replace v29_NEWVARIABLE = var29  if flag_tmp_NEWVARIABLE==5
capture label variable v29_NEWVARIABLE "区分1(男): 特別給与額"


/*----------------------------------------------------------------------
    Description (Base):    "区分2(女)常用労働者数: 前月末"
    Description (Data 1):  "区分2(女)常用労働者数: 前月末"
    Description (Data 2):  "区分2(女)常用労働者数: 前月末"
    Description (Data 3):  "区分2(女)常用労働者数: 前月末"
    Description (Data 4):  "区分2(女)常用労働者数: 前月末"
    Description (Data 5):  "区分2(女)常用労働者数: 前月末"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v30_NEWVARIABLE = "."
capture replace v30_NEWVARIABLE = var30  if flag_tmp_NEWVARIABLE==1
capture replace v30_NEWVARIABLE = var30  if flag_tmp_NEWVARIABLE==2
capture replace v30_NEWVARIABLE = var30  if flag_tmp_NEWVARIABLE==3
capture replace v30_NEWVARIABLE = var30  if flag_tmp_NEWVARIABLE==4
capture replace v30_NEWVARIABLE = var30  if flag_tmp_NEWVARIABLE==5
capture label variable v30_NEWVARIABLE "区分2(女)常用労働者数: 前月末"


/*----------------------------------------------------------------------
    Description (Base):    "区分2(女)常用労働者数: 増加"
    Description (Data 1):  "区分2(女)常用労働者数: 増加"
    Description (Data 2):  "区分2(女)常用労働者数: 増加"
    Description (Data 3):  "区分2(女)常用労働者数: 増加"
    Description (Data 4):  "区分2(女)常用労働者数: 増加"
    Description (Data 5):  "区分2(女)常用労働者数: 増加"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v31_NEWVARIABLE = "."
capture replace v31_NEWVARIABLE = var31  if flag_tmp_NEWVARIABLE==1
capture replace v31_NEWVARIABLE = var31  if flag_tmp_NEWVARIABLE==2
capture replace v31_NEWVARIABLE = var31  if flag_tmp_NEWVARIABLE==3
capture replace v31_NEWVARIABLE = var31  if flag_tmp_NEWVARIABLE==4
capture replace v31_NEWVARIABLE = var31  if flag_tmp_NEWVARIABLE==5
capture label variable v31_NEWVARIABLE "区分2(女)常用労働者数: 増加"


/*----------------------------------------------------------------------
    Description (Base):    "区分2(女)常用労働者数: 減少"
    Description (Data 1):  "区分2(女)常用労働者数: 減少"
    Description (Data 2):  "区分2(女)常用労働者数: 減少"
    Description (Data 3):  "区分2(女)常用労働者数: 減少"
    Description (Data 4):  "区分2(女)常用労働者数: 減少"
    Description (Data 5):  "区分2(女)常用労働者数: 減少"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v32_NEWVARIABLE = "."
capture replace v32_NEWVARIABLE = var32  if flag_tmp_NEWVARIABLE==1
capture replace v32_NEWVARIABLE = var32  if flag_tmp_NEWVARIABLE==2
capture replace v32_NEWVARIABLE = var32  if flag_tmp_NEWVARIABLE==3
capture replace v32_NEWVARIABLE = var32  if flag_tmp_NEWVARIABLE==4
capture replace v32_NEWVARIABLE = var32  if flag_tmp_NEWVARIABLE==5
capture label variable v32_NEWVARIABLE "区分2(女)常用労働者数: 減少"


/*----------------------------------------------------------------------
    Description (Base):    "区分2(女)常用労働者数: 本月末"
    Description (Data 1):  "区分2(女)常用労働者数: 本月末"
    Description (Data 2):  "区分2(女)常用労働者数: 本月末"
    Description (Data 3):  "区分2(女)常用労働者数: 本月末"
    Description (Data 4):  "区分2(女)常用労働者数: 本月末"
    Description (Data 5):  "区分2(女)常用労働者数: 本月末"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v33_NEWVARIABLE = "."
capture replace v33_NEWVARIABLE = var33  if flag_tmp_NEWVARIABLE==1
capture replace v33_NEWVARIABLE = var33  if flag_tmp_NEWVARIABLE==2
capture replace v33_NEWVARIABLE = var33  if flag_tmp_NEWVARIABLE==3
capture replace v33_NEWVARIABLE = var33  if flag_tmp_NEWVARIABLE==4
capture replace v33_NEWVARIABLE = var33  if flag_tmp_NEWVARIABLE==5
capture label variable v33_NEWVARIABLE "区分2(女)常用労働者数: 本月末"


/*----------------------------------------------------------------------
    Description (Base):    "区分2(女)常用労働者数: 本月末のうちパートタイム労働者"
    Description (Data 1):  "区分2(女)常用労働者数: 本月末のうちパートタイム労働者"
    Description (Data 2):  "区分2(女)常用労働者数: 本月末のうちパートタイム労働者"
    Description (Data 3):  "区分2(女)常用労働者数: 本月末のうちパートタイム労働者"
    Description (Data 4):  "区分2(女)常用労働者数: 本月末のうちパートタイム労働者"
    Description (Data 5):  "区分2(女)常用労働者数: 本月末のうちパートタイム労働者"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v34_NEWVARIABLE = "."
capture replace v34_NEWVARIABLE = var34  if flag_tmp_NEWVARIABLE==1
capture replace v34_NEWVARIABLE = var34  if flag_tmp_NEWVARIABLE==2
capture replace v34_NEWVARIABLE = var34  if flag_tmp_NEWVARIABLE==3
capture replace v34_NEWVARIABLE = var34  if flag_tmp_NEWVARIABLE==4
capture replace v34_NEWVARIABLE = var34  if flag_tmp_NEWVARIABLE==5
capture label variable v34_NEWVARIABLE "区分2(女)常用労働者数: 本月末のうちパートタイム労働者"


/*----------------------------------------------------------------------
    Description (Base):    "区分2(女): 出勤日数"
    Description (Data 1):  "区分2(女): 出勤日数"
    Description (Data 2):  "区分2(女): 出勤日数"
    Description (Data 3):  "区分2(女): 出勤日数"
    Description (Data 4):  "区分2(女): 出勤日数"
    Description (Data 5):  "区分2(女): 出勤日数"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v35_NEWVARIABLE = "."
capture replace v35_NEWVARIABLE = var35  if flag_tmp_NEWVARIABLE==1
capture replace v35_NEWVARIABLE = var35  if flag_tmp_NEWVARIABLE==2
capture replace v35_NEWVARIABLE = var35  if flag_tmp_NEWVARIABLE==3
capture replace v35_NEWVARIABLE = var35  if flag_tmp_NEWVARIABLE==4
capture replace v35_NEWVARIABLE = var35  if flag_tmp_NEWVARIABLE==5
capture label variable v35_NEWVARIABLE "区分2(女): 出勤日数"


/*----------------------------------------------------------------------
    Description (Base):    "区分2(女): 所定内労働時間"
    Description (Data 1):  "区分2(女): 所定内労働時間"
    Description (Data 2):  "区分2(女): 所定内労働時間"
    Description (Data 3):  "区分2(女): 所定内労働時間"
    Description (Data 4):  "区分2(女): 所定内労働時間"
    Description (Data 5):  "区分2(女): 所定内労働時間"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v36_NEWVARIABLE = "."
capture replace v36_NEWVARIABLE = var36  if flag_tmp_NEWVARIABLE==1
capture replace v36_NEWVARIABLE = var36  if flag_tmp_NEWVARIABLE==2
capture replace v36_NEWVARIABLE = var36  if flag_tmp_NEWVARIABLE==3
capture replace v36_NEWVARIABLE = var36  if flag_tmp_NEWVARIABLE==4
capture replace v36_NEWVARIABLE = var36  if flag_tmp_NEWVARIABLE==5
capture label variable v36_NEWVARIABLE "区分2(女): 所定内労働時間"


/*----------------------------------------------------------------------
    Description (Base):    "区分2(女): 所定外労働時間"
    Description (Data 1):  "区分2(女): 所定外労働時間"
    Description (Data 2):  "区分2(女): 所定外労働時間"
    Description (Data 3):  "区分2(女): 所定外労働時間"
    Description (Data 4):  "区分2(女): 所定外労働時間"
    Description (Data 5):  "区分2(女): 所定外労働時間"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v37_NEWVARIABLE = "."
capture replace v37_NEWVARIABLE = var37  if flag_tmp_NEWVARIABLE==1
capture replace v37_NEWVARIABLE = var37  if flag_tmp_NEWVARIABLE==2
capture replace v37_NEWVARIABLE = var37  if flag_tmp_NEWVARIABLE==3
capture replace v37_NEWVARIABLE = var37  if flag_tmp_NEWVARIABLE==4
capture replace v37_NEWVARIABLE = var37  if flag_tmp_NEWVARIABLE==5
capture label variable v37_NEWVARIABLE "区分2(女): 所定外労働時間"


/*----------------------------------------------------------------------
    Description (Base):    "区分2(女): きまって支給する現金給与額"
    Description (Data 1):  "区分2(女): きまって支給する現金給与額"
    Description (Data 2):  "区分2(女): きまって支給する現金給与額"
    Description (Data 3):  "区分2(女): きまって支給する現金給与額"
    Description (Data 4):  "区分2(女): きまって支給する現金給与額"
    Description (Data 5):  "区分2(女): きまって支給する現金給与額"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v38_NEWVARIABLE = "."
capture replace v38_NEWVARIABLE = var38  if flag_tmp_NEWVARIABLE==1
capture replace v38_NEWVARIABLE = var38  if flag_tmp_NEWVARIABLE==2
capture replace v38_NEWVARIABLE = var38  if flag_tmp_NEWVARIABLE==3
capture replace v38_NEWVARIABLE = var38  if flag_tmp_NEWVARIABLE==4
capture replace v38_NEWVARIABLE = var38  if flag_tmp_NEWVARIABLE==5
capture label variable v38_NEWVARIABLE "区分2(女): きまって支給する現金給与額"


/*----------------------------------------------------------------------
    Description (Base):    "区分2(女): 特別給与額"
    Description (Data 1):  "区分2(女): 特別給与額"
    Description (Data 2):  "区分2(女): 特別給与額"
    Description (Data 3):  "区分2(女): 特別給与額"
    Description (Data 4):  "区分2(女): 特別給与額"
    Description (Data 5):  "区分2(女): 特別給与額"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v39_NEWVARIABLE = "."
capture replace v39_NEWVARIABLE = var39  if flag_tmp_NEWVARIABLE==1
capture replace v39_NEWVARIABLE = var39  if flag_tmp_NEWVARIABLE==2
capture replace v39_NEWVARIABLE = var39  if flag_tmp_NEWVARIABLE==3
capture replace v39_NEWVARIABLE = var39  if flag_tmp_NEWVARIABLE==4
capture replace v39_NEWVARIABLE = var39  if flag_tmp_NEWVARIABLE==5
capture label variable v39_NEWVARIABLE "区分2(女): 特別給与額"


/*----------------------------------------------------------------------
    Description (Base):    "区分3(パートタイム労働者)常用労働者数: 前月末"
    Description (Data 1):  "区分3(パートタイム労働者)常用労働者数: 前月末"
    Description (Data 2):  "区分3(パートタイム労働者)常用労働者数: 前月末"
    Description (Data 3):  "区分3(パートタイム労働者)常用労働者数: 前月末"
    Description (Data 4):  "区分3(パートタイム労働者)常用労働者数: 前月末"
    Description (Data 5):  "区分3(パートタイム労働者)常用労働者数: 前月末"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v40_NEWVARIABLE = "."
capture replace v40_NEWVARIABLE = var40  if flag_tmp_NEWVARIABLE==1
capture replace v40_NEWVARIABLE = var40  if flag_tmp_NEWVARIABLE==2
capture replace v40_NEWVARIABLE = var40  if flag_tmp_NEWVARIABLE==3
capture replace v40_NEWVARIABLE = var40  if flag_tmp_NEWVARIABLE==4
capture replace v40_NEWVARIABLE = var40  if flag_tmp_NEWVARIABLE==5
capture label variable v40_NEWVARIABLE "区分3(パートタイム労働者)常用労働者数: 前月末"


/*----------------------------------------------------------------------
    Description (Base):    "区分3(パートタイム労働者)常用労働者数: 増加"
    Description (Data 1):  "区分3(パートタイム労働者)常用労働者数: 増加"
    Description (Data 2):  "区分3(パートタイム労働者)常用労働者数: 増加"
    Description (Data 3):  "区分3(パートタイム労働者)常用労働者数: 増加"
    Description (Data 4):  "区分3(パートタイム労働者)常用労働者数: 増加"
    Description (Data 5):  "区分3(パートタイム労働者)常用労働者数: 増加"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v41_NEWVARIABLE = "."
capture replace v41_NEWVARIABLE = var41  if flag_tmp_NEWVARIABLE==1
capture replace v41_NEWVARIABLE = var41  if flag_tmp_NEWVARIABLE==2
capture replace v41_NEWVARIABLE = var41  if flag_tmp_NEWVARIABLE==3
capture replace v41_NEWVARIABLE = var41  if flag_tmp_NEWVARIABLE==4
capture replace v41_NEWVARIABLE = var41  if flag_tmp_NEWVARIABLE==5
capture label variable v41_NEWVARIABLE "区分3(パートタイム労働者)常用労働者数: 増加"


/*----------------------------------------------------------------------
    Description (Base):    "区分3(パートタイム労働者)常用労働者数: 減少"
    Description (Data 1):  "区分3(パートタイム労働者)常用労働者数: 減少"
    Description (Data 2):  "区分3(パートタイム労働者)常用労働者数: 減少"
    Description (Data 3):  "区分3(パートタイム労働者)常用労働者数: 減少"
    Description (Data 4):  "区分3(パートタイム労働者)常用労働者数: 減少"
    Description (Data 5):  "区分3(パートタイム労働者)常用労働者数: 減少"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v42_NEWVARIABLE = "."
capture replace v42_NEWVARIABLE = var42  if flag_tmp_NEWVARIABLE==1
capture replace v42_NEWVARIABLE = var42  if flag_tmp_NEWVARIABLE==2
capture replace v42_NEWVARIABLE = var42  if flag_tmp_NEWVARIABLE==3
capture replace v42_NEWVARIABLE = var42  if flag_tmp_NEWVARIABLE==4
capture replace v42_NEWVARIABLE = var42  if flag_tmp_NEWVARIABLE==5
capture label variable v42_NEWVARIABLE "区分3(パートタイム労働者)常用労働者数: 減少"


/*----------------------------------------------------------------------
    Description (Base):    "区分3(パートタイム労働者)常用労働者数: 本月末"
    Description (Data 1):  "区分3(パートタイム労働者)常用労働者数: 本月末"
    Description (Data 2):  "区分3(パートタイム労働者)常用労働者数: 本月末"
    Description (Data 3):  "区分3(パートタイム労働者)常用労働者数: 本月末"
    Description (Data 4):  "区分3(パートタイム労働者)常用労働者数: 本月末"
    Description (Data 5):  "区分3(パートタイム労働者)常用労働者数: 本月末"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v43_NEWVARIABLE = "."
capture replace v43_NEWVARIABLE = var43  if flag_tmp_NEWVARIABLE==1
capture replace v43_NEWVARIABLE = var43  if flag_tmp_NEWVARIABLE==2
capture replace v43_NEWVARIABLE = var43  if flag_tmp_NEWVARIABLE==3
capture replace v43_NEWVARIABLE = var43  if flag_tmp_NEWVARIABLE==4
capture replace v43_NEWVARIABLE = var43  if flag_tmp_NEWVARIABLE==5
capture label variable v43_NEWVARIABLE "区分3(パートタイム労働者)常用労働者数: 本月末"


/*----------------------------------------------------------------------
    Description (Base):    "区分3(パートタイム労働者): 出勤日数"
    Description (Data 1):  "区分3(パートタイム労働者): 出勤日数"
    Description (Data 2):  "区分3(パートタイム労働者): 出勤日数"
    Description (Data 3):  "区分3(パートタイム労働者): 出勤日数"
    Description (Data 4):  "区分3(パートタイム労働者): 出勤日数"
    Description (Data 5):  "区分3(パートタイム労働者): 出勤日数"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v44_NEWVARIABLE = "."
capture replace v44_NEWVARIABLE = var44  if flag_tmp_NEWVARIABLE==1
capture replace v44_NEWVARIABLE = var44  if flag_tmp_NEWVARIABLE==2
capture replace v44_NEWVARIABLE = var44  if flag_tmp_NEWVARIABLE==3
capture replace v44_NEWVARIABLE = var44  if flag_tmp_NEWVARIABLE==4
capture replace v44_NEWVARIABLE = var44  if flag_tmp_NEWVARIABLE==5
capture label variable v44_NEWVARIABLE "区分3(パートタイム労働者): 出勤日数"


/*----------------------------------------------------------------------
    Description (Base):    "区分3(パートタイム労働者): 所定内労働時間"
    Description (Data 1):  "区分3(パートタイム労働者): 所定内労働時間"
    Description (Data 2):  "区分3(パートタイム労働者): 所定内労働時間"
    Description (Data 3):  "区分3(パートタイム労働者): 所定内労働時間"
    Description (Data 4):  "区分3(パートタイム労働者): 所定内労働時間"
    Description (Data 5):  "区分3(パートタイム労働者): 所定内労働時間"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v45_NEWVARIABLE = "."
capture replace v45_NEWVARIABLE = var45  if flag_tmp_NEWVARIABLE==1
capture replace v45_NEWVARIABLE = var45  if flag_tmp_NEWVARIABLE==2
capture replace v45_NEWVARIABLE = var45  if flag_tmp_NEWVARIABLE==3
capture replace v45_NEWVARIABLE = var45  if flag_tmp_NEWVARIABLE==4
capture replace v45_NEWVARIABLE = var45  if flag_tmp_NEWVARIABLE==5
capture label variable v45_NEWVARIABLE "区分3(パートタイム労働者): 所定内労働時間"


/*----------------------------------------------------------------------
    Description (Base):    "区分3(パートタイム労働者): 所定外労働時間"
    Description (Data 1):  "区分3(パートタイム労働者): 所定外労働時間"
    Description (Data 2):  "区分3(パートタイム労働者): 所定外労働時間"
    Description (Data 3):  "区分3(パートタイム労働者): 所定外労働時間"
    Description (Data 4):  "区分3(パートタイム労働者): 所定外労働時間"
    Description (Data 5):  "区分3(パートタイム労働者): 所定外労働時間"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v46_NEWVARIABLE = "."
capture replace v46_NEWVARIABLE = var46  if flag_tmp_NEWVARIABLE==1
capture replace v46_NEWVARIABLE = var46  if flag_tmp_NEWVARIABLE==2
capture replace v46_NEWVARIABLE = var46  if flag_tmp_NEWVARIABLE==3
capture replace v46_NEWVARIABLE = var46  if flag_tmp_NEWVARIABLE==4
capture replace v46_NEWVARIABLE = var46  if flag_tmp_NEWVARIABLE==5
capture label variable v46_NEWVARIABLE "区分3(パートタイム労働者): 所定外労働時間"


/*----------------------------------------------------------------------
    Description (Base):    "区分3(パートタイム労働者): きまって支給する現金給与額"
    Description (Data 1):  "区分3(パートタイム労働者): きまって支給する現金給与額"
    Description (Data 2):  "区分3(パートタイム労働者): きまって支給する現金給与額"
    Description (Data 3):  "区分3(パートタイム労働者): きまって支給する現金給与額"
    Description (Data 4):  "区分3(パートタイム労働者): きまって支給する現金給与額"
    Description (Data 5):  "区分3(パートタイム労働者): きまって支給する現金給与額"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v47_NEWVARIABLE = "."
capture replace v47_NEWVARIABLE = var47  if flag_tmp_NEWVARIABLE==1
capture replace v47_NEWVARIABLE = var47  if flag_tmp_NEWVARIABLE==2
capture replace v47_NEWVARIABLE = var47  if flag_tmp_NEWVARIABLE==3
capture replace v47_NEWVARIABLE = var47  if flag_tmp_NEWVARIABLE==4
capture replace v47_NEWVARIABLE = var47  if flag_tmp_NEWVARIABLE==5
capture label variable v47_NEWVARIABLE "区分3(パートタイム労働者): きまって支給する現金給与額"


/*----------------------------------------------------------------------
    Description (Base):    "区分3(パートタイム労働者): 特別給与額"
    Description (Data 1):  "区分3(パートタイム労働者): 特別給与額"
    Description (Data 2):  "区分3(パートタイム労働者): 特別給与額"
    Description (Data 3):  "区分3(パートタイム労働者): 特別給与額"
    Description (Data 4):  "区分3(パートタイム労働者): 特別給与額"
    Description (Data 5):  "区分3(パートタイム労働者): 特別給与額"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v48_NEWVARIABLE = "."
capture replace v48_NEWVARIABLE = var48  if flag_tmp_NEWVARIABLE==1
capture replace v48_NEWVARIABLE = var48  if flag_tmp_NEWVARIABLE==2
capture replace v48_NEWVARIABLE = var48  if flag_tmp_NEWVARIABLE==3
capture replace v48_NEWVARIABLE = var48  if flag_tmp_NEWVARIABLE==4
capture replace v48_NEWVARIABLE = var48  if flag_tmp_NEWVARIABLE==5
capture label variable v48_NEWVARIABLE "区分3(パートタイム労働者): 特別給与額"


/*----------------------------------------------------------------------
    Description (Base):    "区分4(計): 超過労働時間給与"
    Description (Data 1):  "区分4(計): 超過労働時間給与"
    Description (Data 2):  "区分4(計): 超過労働時間給与"
    Description (Data 3):  "区分4(計): 超過労働時間給与"
    Description (Data 4):  "区分4(計): 超過労働時間給与"
    Description (Data 5):  "区分4(計): 超過労働時間給与"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v49_NEWVARIABLE = "."
capture replace v49_NEWVARIABLE = var49  if flag_tmp_NEWVARIABLE==1
capture replace v49_NEWVARIABLE = var49  if flag_tmp_NEWVARIABLE==2
capture replace v49_NEWVARIABLE = var49  if flag_tmp_NEWVARIABLE==3
capture replace v49_NEWVARIABLE = var49  if flag_tmp_NEWVARIABLE==4
capture replace v49_NEWVARIABLE = var49  if flag_tmp_NEWVARIABLE==5
capture label variable v49_NEWVARIABLE "区分4(計): 超過労働時間給与"


/*----------------------------------------------------------------------
    Description (Base):    "区分4(計): 超過労働時間給与(パートタイム労働者)"
    Description (Data 1):  "区分4(計): 超過労働時間給与(パートタイム労働者)"
    Description (Data 2):  "区分4(計): 超過労働時間給与(パートタイム労働者)"
    Description (Data 3):  "区分4(計): 超過労働時間給与(パートタイム労働者)"
    Description (Data 4):  "区分4(計): 超過労働時間給与(パートタイム労働者)"
    Description (Data 5):  "区分4(計): 超過労働時間給与(パートタイム労働者)"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v50_NEWVARIABLE = "."
capture replace v50_NEWVARIABLE = var50  if flag_tmp_NEWVARIABLE==1
capture replace v50_NEWVARIABLE = var50  if flag_tmp_NEWVARIABLE==2
capture replace v50_NEWVARIABLE = var50  if flag_tmp_NEWVARIABLE==3
capture replace v50_NEWVARIABLE = var50  if flag_tmp_NEWVARIABLE==4
capture replace v50_NEWVARIABLE = var50  if flag_tmp_NEWVARIABLE==5
capture label variable v50_NEWVARIABLE "区分4(計): 超過労働時間給与(パートタイム労働者)"


/*----------------------------------------------------------------------
    Description (Base):    "区分4(計): 特別給与額"
    Description (Data 1):  "区分4(計): 特別給与額"
    Description (Data 2):  "区分4(計): 特別給与額"
    Description (Data 3):  "区分4(計): 特別給与額"
    Description (Data 4):  "区分4(計): 特別給与額"
    Description (Data 5):  "区分4(計): 特別給与額"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v51_NEWVARIABLE = "."
capture replace v51_NEWVARIABLE = var51  if flag_tmp_NEWVARIABLE==1
capture replace v51_NEWVARIABLE = var51  if flag_tmp_NEWVARIABLE==2
capture replace v51_NEWVARIABLE = var51  if flag_tmp_NEWVARIABLE==3
capture replace v51_NEWVARIABLE = var51  if flag_tmp_NEWVARIABLE==4
capture replace v51_NEWVARIABLE = var51  if flag_tmp_NEWVARIABLE==5
capture label variable v51_NEWVARIABLE "区分4(計): 特別給与額"


/*----------------------------------------------------------------------
    Description (Base):    "変動理由: 定昇を実施した"
    Description (Data 1):  "変動理由: 定昇を実施した"
    Description (Data 2):  "変動理由: 定昇を実施した"
    Description (Data 3):  "変動理由: 定昇を実施した"
    Description (Data 4):  "変動理由: 定昇を実施した"
    Description (Data 5):  "変動理由: 定昇を実施した"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v52_NEWVARIABLE = "."
capture replace v52_NEWVARIABLE = var52  if flag_tmp_NEWVARIABLE==1
capture replace v52_NEWVARIABLE = var52  if flag_tmp_NEWVARIABLE==2
capture replace v52_NEWVARIABLE = var52  if flag_tmp_NEWVARIABLE==3
capture replace v52_NEWVARIABLE = var52  if flag_tmp_NEWVARIABLE==4
capture replace v52_NEWVARIABLE = var52  if flag_tmp_NEWVARIABLE==5
capture label variable v52_NEWVARIABLE "変動理由: 定昇を実施した"


/*----------------------------------------------------------------------
    Description (Base):    "変動理由: ベースアップを実施した"
    Description (Data 1):  "変動理由: ベースアップを実施した"
    Description (Data 2):  "変動理由: ベースアップを実施した"
    Description (Data 3):  "変動理由: ベースアップを実施した"
    Description (Data 4):  "変動理由: ベースアップを実施した"
    Description (Data 5):  "変動理由: ベースアップを実施した"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v53_NEWVARIABLE = "."
capture replace v53_NEWVARIABLE = var53  if flag_tmp_NEWVARIABLE==1
capture replace v53_NEWVARIABLE = var53  if flag_tmp_NEWVARIABLE==2
capture replace v53_NEWVARIABLE = var53  if flag_tmp_NEWVARIABLE==3
capture replace v53_NEWVARIABLE = var53  if flag_tmp_NEWVARIABLE==4
capture replace v53_NEWVARIABLE = var53  if flag_tmp_NEWVARIABLE==5
capture label variable v53_NEWVARIABLE "変動理由: ベースアップを実施した"


/*----------------------------------------------------------------------
    Description (Base):    "変動理由: 操業短縮、一時休業を実施した"
    Description (Data 1):  "変動理由: 操業短縮、一時休業を実施した"
    Description (Data 2):  "変動理由: 操業短縮、一時休業を実施した"
    Description (Data 3):  "変動理由: 操業短縮、一時休業を実施した"
    Description (Data 4):  "変動理由: 操業短縮、一時休業を実施した"
    Description (Data 5):  "変動理由: 操業短縮、一時休業を実施した"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v54_NEWVARIABLE = "."
capture replace v54_NEWVARIABLE = var54  if flag_tmp_NEWVARIABLE==1
capture replace v54_NEWVARIABLE = var54  if flag_tmp_NEWVARIABLE==2
capture replace v54_NEWVARIABLE = var54  if flag_tmp_NEWVARIABLE==3
capture replace v54_NEWVARIABLE = var54  if flag_tmp_NEWVARIABLE==4
capture replace v54_NEWVARIABLE = var54  if flag_tmp_NEWVARIABLE==5
capture label variable v54_NEWVARIABLE "変動理由: 操業短縮、一時休業を実施した"


/*----------------------------------------------------------------------
    Description (Base):    "変動理由: 休日に操業、営業等の事業活動を行った"
    Description (Data 1):  "変動理由: 休日に操業、営業等の事業活動を行った"
    Description (Data 2):  "変動理由: 休日に操業、営業等の事業活動を行った"
    Description (Data 3):  "変動理由: 休日に操業、営業等の事業活動を行った"
    Description (Data 4):  "変動理由: 休日に操業、営業等の事業活動を行った"
    Description (Data 5):  "変動理由: 休日に操業、営業等の事業活動を行った"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v55_NEWVARIABLE = "."
capture replace v55_NEWVARIABLE = var55  if flag_tmp_NEWVARIABLE==1
capture replace v55_NEWVARIABLE = var55  if flag_tmp_NEWVARIABLE==2
capture replace v55_NEWVARIABLE = var55  if flag_tmp_NEWVARIABLE==3
capture replace v55_NEWVARIABLE = var55  if flag_tmp_NEWVARIABLE==4
capture replace v55_NEWVARIABLE = var55  if flag_tmp_NEWVARIABLE==5
capture label variable v55_NEWVARIABLE "変動理由: 休日に操業、営業等の事業活動を行った"


/*----------------------------------------------------------------------
    Description (Base):    "変動理由: 制度上の週所定労働時間の短縮を実施した"
    Description (Data 1):  "変動理由: 制度上の週所定労働時間の短縮を実施した"
    Description (Data 2):  "変動理由: 制度上の週所定労働時間の短縮を実施した"
    Description (Data 3):  "変動理由: 制度上の週所定労働時間の短縮を実施した"
    Description (Data 4):  "変動理由: 制度上の週所定労働時間の短縮を実施した"
    Description (Data 5):  "変動理由: 制度上の週所定労働時間の短縮を実施した"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v56_NEWVARIABLE = "."
capture replace v56_NEWVARIABLE = var56  if flag_tmp_NEWVARIABLE==1
capture replace v56_NEWVARIABLE = var56  if flag_tmp_NEWVARIABLE==2
capture replace v56_NEWVARIABLE = var56  if flag_tmp_NEWVARIABLE==3
capture replace v56_NEWVARIABLE = var56  if flag_tmp_NEWVARIABLE==4
capture replace v56_NEWVARIABLE = var56  if flag_tmp_NEWVARIABLE==5
capture label variable v56_NEWVARIABLE "変動理由: 制度上の週所定労働時間の短縮を実施した"


/*----------------------------------------------------------------------
    Description (Base):    "変動理由: 夏休みなど、週休以外の休日を増やした"
    Description (Data 1):  "変動理由: 夏休みなど、週休以外の休日を増やした"
    Description (Data 2):  "変動理由: 夏休みなど、週休以外の休日を増やした"
    Description (Data 3):  "変動理由: 夏休みなど、週休以外の休日を増やした"
    Description (Data 4):  "変動理由: 夏休みなど、週休以外の休日を増やした"
    Description (Data 5):  "変動理由: 夏休みなど、週休以外の休日を増やした"

    Values (Base):    
    Values (Data 1):  
    Values (Data 2):  
    Values (Data 3):  
    Values (Data 4):  
    Values (Data 5):  

----------------------------------------------------------------------*/
gen v57_NEWVARIABLE = "."
capture replace v57_NEWVARIABLE = var57  if flag_tmp_NEWVARIABLE==1
capture replace v57_NEWVARIABLE = var57  if flag_tmp_NEWVARIABLE==2
capture replace v57_NEWVARIABLE = var57  if flag_tmp_NEWVARIABLE==3
capture replace v57_NEWVARIABLE = var57  if flag_tmp_NEWVARIABLE==4
capture replace v57_NEWVARIABLE = var57  if flag_tmp_NEWVARIABLE==5
capture label variable v57_NEWVARIABLE "変動理由: 夏休みなど、週休以外の休日を増やした"


keep *_NEWVARIABLE
rename *_NEWVARIABLE *
