/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: D:/GitHub/mic-wagestat/layout/ESS/S62 集計用個別データ.xls
    Date: 2021/03/12 16:37:32
-----------------------------------------------------------------------------*/


#delimit ;
    quietly infix
        str CHO_YEAR 4-7
        str CHO_MONTH 8-9
        str CHIKI_KEN 12-13
        str CHIKI_CITY 14-16
        str CHIKI_CHONO 18-21
        str WAT_SHUKEI 67-78
        str S_RENBAN 80-81
        str S_ORGBANGO 82-83
        str S_SETIINNO 84-85
        str S_IPPAN 86-86
        str S_KAZOKURUI 87-87
        str S_JIN0 100-100
        str S_JIN1 101-101
        str S_JIN2 102-102
        str S_JIN3 103-103
        str S_JIN4 104-104
        str S_JIN5 105-105
        str S_JIN6 106-106
        str S_JIN7 107-107
        str S_JIN8 108-108
        str S_JIN9 109-109
        str S_JIN10 110-110
        str S_JIN11 111-111
        str S_JIN12 112-112
        str S_JIN13 113-113
        str S_JIN14 114-114
        str S_JIN15MI 115-116
        str S_JIN15IJO 117-118
        str S_OMOSYU 133-134
        str S_JYU1 135-135
        str S_JYU2 136-136
        str S_JYU3 137-137
        str S_JYU4 138-138
        str S_JYU5 139-139
        str S_JYU6 140-140
        str S_JYU7 141-141
        str S_JYU8 142-142
        str S_JYU9 143-143
        str S_JYU10 144-144
        str S_SHOTOKU 146-147
        str K_SEX 150-150
        str K_TUZUKI 152-153
        str K_NENGO 154-154
        str K_NEN 155-156
        str K_TUKI 157-157
        str K_AGE 158-160
        str K_AGE5 161-162
        str K_AGE10 163-163
        str K_HAIGU 164-164
        str K_ZENJYU 165-165
        str K_ZENJYUKEN 166-167
        str K_SOTUGYO 171-171
        str K_GAKKO 172-172
        str K_SYUGYO 176-176
        str YH_JYUTII 182-182
        str YH_KOSHO7 184-184
        str YH_KEIEI 186-186
        str YH_NOHINOU 188-188
        str YH_SAN3 189-189
        str YH_SANDAI 190-191
        str YH_SANM 192-193
        str YH_SANCHU 194-195
        str YH_SHODAI 196-197
        str YH_SHOM 198-199
        str YH_KAIKYU11 202-203
        str YH_NISSU 205-205
        str YH_JYUGYO 206-206
        str YH_JIKAN 208-208
        str YH_SHOTOKU 209-210
        str YH_SYUISIKI 213-213
        str YH_SYUZOGEN 214-214
        str YH_SYURIYU 215-215
        str YH_SYUKEITAI 216-216
        str YH_KATUDO 217-217
        str YF_FUKU 219-219
        str YF_JYUTII 220-220
        str YF_NOHINOU 221-221
        str YF_SAN3 222-222
        str YF_SANDAI 223-224
        str YF_SANCHU 225-226
        str YF_SHOTOKU 227-227
        str YZ_KEIZOKU 230-230
        str YZ_KEINEN 233-234
        str YZ_SYUGYO 237-237
        str YZ_SYURIYU 238-238
        str YZ_ZENUMU 239-239
        str M_SYUKIBOU 242-242
        str M_SYURIYU 243-243
        str M_SYUSIGOTO 244-244
        str M_SYUKEITAI 245-245
        str M_KYUKATUDO 246-246
        str M_KYUHIRIYU 247-247
        str M_KYUHOHO 248-248
        str M_KYUKIKAN 249-249
        str M_KIBOJIKI 250-250
        str M_ZSYUGYO 251-251
        str M_ZENUMU 252-252
        str Z_RIJIKI2 256-256
        str Z_RIJIKINEN 257-258
        str Z_RIYU 266-267
        str Z_JYUTII 268-268
        str Z_NOHINOU 269-269
        str Z_SAN3 270-270
        str Z_SANDAI 271-272
        str Z_SANCHU 273-274
        str Z_SHODAI 275-276
        str Z_SHOM 277-278
        str Z_KAIKYU 279-280
        str Z_KEINEN 281-282
    using "${path_data}/chosa/raw/210119　就業構造基本統計調査調査票情報データ/提供データ（統計委員会）/提供データ/L5_1987_RCD_CB1-KK_A_S.TXT";
#delimit cr
