capture program drop SyokuCodeH17
program define SyokuCodeH17
	syntax varlist(min=1 max=1 numeric)
	
	capture label drop `varlist'
	label define `varlist' 101 "部長級"
	label define `varlist' 102 "課長級", add
	label define `varlist' 103 "係長級", add
	label define `varlist' 104 "職長級", add
	label define `varlist' 105 "その他役職", add
	label define `varlist' 201 "自然科学系研究者", add
	label define `varlist' 202 "化学分析員", add
	label define `varlist' 203 "技術士", add
	label define `varlist' 204 "一級建築士", add
	label define `varlist' 205 "測量技術者", add
	label define `varlist' 206 "システム・エンジニア", add
	label define `varlist' 207 "プログラマー", add
	label define `varlist' 208 "医師", add
	label define `varlist' 209 "歯科医師", add
	label define `varlist' 210 "獣医師", add
	label define `varlist' 211 "薬剤師", add
	label define `varlist' 212 "看護師", add
	label define `varlist' 213 "准看護師", add
	label define `varlist' 214 "看護補助者", add
	label define `varlist' 215 "診療放射線・診療エックス線技師", add
	label define `varlist' 216 "臨床検査技師", add
	label define `varlist' 217 "理学療法士、作業療法士", add
	label define `varlist' 218 "歯科衛生士", add
	label define `varlist' 219 "歯科技工士", add
	label define `varlist' 220 "栄養士", add
	label define `varlist' 221 "保育士（保母・保父）", add
	label define `varlist' 222 "介護支援専門員（ケアマネージャー）", add
	label define `varlist' 223 "ホームヘルパー", add
	label define `varlist' 224 "福祉施設介護員", add
	label define `varlist' 225 "弁護士", add
	label define `varlist' 226 "公認会計士、税理士", add
	label define `varlist' 227 "社会保険労務士", add
	label define `varlist' 228 "不動産鑑定士", add
	label define `varlist' 229 "幼稚園教諭", add
	label define `varlist' 230 "高等学校教員", add
	label define `varlist' 231 "大学教授", add
	label define `varlist' 232 "大学准教授", add
	label define `varlist' 233 "大学講師", add
	label define `varlist' 234 "各種学校・専修学校教員", add
	label define `varlist' 235 "個人教師、塾・予備校講師", add
	label define `varlist' 236 "記者", add
	label define `varlist' 237 "デザイナー", add
	label define `varlist' 301 "ワープロ・オペレーター", add
	label define `varlist' 302 "キーパンチャー", add
	label define `varlist' 303 "電子計算機オペレーター", add
	label define `varlist' 401 "百貨店店員", add
	label define `varlist' 402 "販売店員（百貨店店員を除く。）", add
	label define `varlist' 403 "スーパー店チェッカー", add
	label define `varlist' 404 "自動車外交販売員", add
	label define `varlist' 405 "家庭用品外交販売員", add
	label define `varlist' 406 "保険外交員", add
	label define `varlist' 501 "理容・美容師", add
	label define `varlist' 502 "洗たく工", add
	label define `varlist' 503 "調理士", add
	label define `varlist' 504 "調理士見習", add
	label define `varlist' 505 "給仕従事者", add
	label define `varlist' 506 "娯楽接客員", add
	label define `varlist' 601 "警備員", add
	label define `varlist' 602 "守衛", add
	label define `varlist' 701 "電車運転士", add
	label define `varlist' 702 "電車車掌", add
	label define `varlist' 703 "旅客掛", add
	label define `varlist' 704 "自家用乗用自動車運転手", add
	label define `varlist' 705 "自家用貨物自動車運転者", add
	label define `varlist' 706 "タクシー運転者", add
	label define `varlist' 707 "営業用バス運転者", add
	label define `varlist' 708 "営業用大型貨物自動車運転者", add
	label define `varlist' 709 "営業用普通・小型貨物自動車運転者", add
	label define `varlist' 710 "航空機操縦士", add
	label define `varlist' 711 "航空機客室乗務員", add
	label define `varlist' 801 "製鋼工", add
	label define `varlist' 802 "非鉄金属精錬工", add
	label define `varlist' 803 "鋳物工", add
	label define `varlist' 804 "型鍛造工", add
	label define `varlist' 805 "鉄鋼熱処理工", add
	label define `varlist' 806 "圧延伸張工", add
	label define `varlist' 807 "金属検査工", add
	label define `varlist' 808 "一般化学工", add
	label define `varlist' 809 "化繊紡糸工", add
	label define `varlist' 810 "ガラス製品工", add
	label define `varlist' 811 "陶磁器工", add
	label define `varlist' 812 "旋盤工", add
	label define `varlist' 813 "フライス盤工", add
	label define `varlist' 814 "金属プレス工", add
	label define `varlist' 815 "鉄工", add
	label define `varlist' 816 "板金工", add
	label define `varlist' 817 "電気めっき工", add
	label define `varlist' 818 "バフ研磨工", add
	label define `varlist' 819 "仕上工", add
	label define `varlist' 820 "溶接工", add
	label define `varlist' 821 "機械組立工", add
	label define `varlist' 822 "機械検査工", add
	label define `varlist' 823 "機械修理工", add
	label define `varlist' 824 "重電機器組立工", add
	label define `varlist' 825 "通信機器組立工", add
	label define `varlist' 826 "半導体チップ製造工", add
	label define `varlist' 827 "プリント配線工", add
	label define `varlist' 828 "軽電機器検査工", add
	label define `varlist' 829 "自動車組立工", add
	label define `varlist' 830 "自動車整備工", add
	label define `varlist' 831 "パン・洋生菓子製造工", add
	label define `varlist' 832 "精紡工", add
	label define `varlist' 833 "織布工", add
	label define `varlist' 834 "洋裁工", add
	label define `varlist' 835 "ミシン縫製工", add
	label define `varlist' 836 "製材工", add
	label define `varlist' 837 "木型工", add
	label define `varlist' 838 "家具工", add
	label define `varlist' 839 "建具製造工", add
	label define `varlist' 840 "製紙工", add
	label define `varlist' 841 "紙器工", add
	label define `varlist' 842 "プロセス製版工", add
	label define `varlist' 843 "オフセット印刷工", add
	label define `varlist' 844 "合成樹脂製品成形工", add
	label define `varlist' 845 "金属・建築塗装工", add
	label define `varlist' 846 "機械製図工", add
	label define `varlist' 847 "ボイラー工", add
	label define `varlist' 848 "クレーン運転工", add
	label define `varlist' 849 "建設機械運転工", add
	label define `varlist' 850 "玉掛け作業員", add
	label define `varlist' 851 "発電・変電工", add
	label define `varlist' 852 "電気工", add
	label define `varlist' 853 "掘削・発破工", add
	label define `varlist' 854 "型枠大工", add
	label define `varlist' 855 "とび工", add
	label define `varlist' 856 "鉄筋工", add
	label define `varlist' 857 "大工", add
	label define `varlist' 858 "左官", add
	label define `varlist' 859 "配管工", add
	label define `varlist' 860 "はつり工", add
	label define `varlist' 861 "土工", add
	label define `varlist' 862 "港湾荷役作業員", add
	label define `varlist' 863 "ビル清掃員", add
	label define `varlist' 864 "用務員", add
	
	label values `varlist' `varlist'
end
