/*-----------------------------------------------------------------------------
    <README>
    This do-file is generated from the python program provided
    in 'https://github.com/Takahiro-Toriyabe/MicroDataCleaning'.
        _const.do:    Import fixed-length data
        _var.do:      Put variable labels
        _val.do:      Put value labels
        _validate.do: Check if the data seems correctly imported
        rename.do:    Rename variable to harmonize several data

    WARNING:
        1. The generated do-files do not necessarily correct. If you find
           something wrong regarding the program or the resulting do-file(s),
           please report at the above GitHub web page.

        2. _validate.do checks if each variable has the values that it is
           supposed to have (only for categorical variables).

        3. rename.do is generated by finding a variable with a similar variable
           description and, if any, a similar variable name from the base data.
           So it is quite likely that some variables are renamed incorrectly.
           Please check and modify rename.do.

        4. Although value labels are put for each individual data, the labels
           are not put for the appended data, because the categories for each
           variable are very likely to be inconsistent across years.

        5. There is no file to make variable values consistent across different
           data.


    Source: 
    Date: 2020/08/11 22:29:38
-----------------------------------------------------------------------------*/


capture label variable KYOKUSYO "局署"
capture label variable SEIRI "番号"
capture label variable ERROR_FLG "エラーフラグ"
capture label variable ITIREN_NO "一連番号"
capture label variable SEIBETU "性別"
capture label variable NENREI "満年齢"
capture label variable KINZOKU_NEN "勤続年数"
capture label variable KYUYO_TUKI "給与を支給した月数"
capture label variable SYOKUMU "職務"
capture label variable NENTYO "年末調整"
capture label variable HAIGU_UMU "控除対象配偶者"
capture label variable IPPAN_HUYO "扶養親族数: 一般の控除対象扶養親族"
capture label variable TOKUTEI_HUYO "扶養親族数: 特定扶養親族"
capture label variable DOKYO_ROSIN_ETC "扶養親族数: 老人扶養親族(同居老親等)"
capture label variable IPPAN_ROJIN "扶養親族数: 老人扶養親族(一般)"
capture label variable HUYO_SIN "扶養親族数: 計"
capture label variable SYOGAI "扶養親族数: うち一般の障害者"
capture label variable DOKYO_TOKUSYO "扶養親族数: うち同居特別障害者"
capture label variable HI_DOKYO_TOKUSYO "扶養親族数: うち非同居特別障害者"
capture label variable SYOGAI_KOJO "本人控除: 障害者控除(一般)"
capture label variable TOKU_SYOGAI_KOJO "本人控除: 障害者控除(特別)"
capture label variable TOKU_KAHU_KOJO "本人控除: 寡婦控除(特別)"
capture label variable IPPAN_KAHU_KOJO "本人控除: 寡婦控除(一般)"
capture label variable KAHU_KOJO "本人控除: 寡夫控除"
capture label variable KINRO_KOJO "本人控除: 勤労学生控除"
capture label variable KYUYO_TEATE "給与の金額: 給料・手当等"
capture label variable SYOYO "給与の金額: 賞与等"
capture label variable KYUYOGAKU_KEI "給与の金額: 計"
capture label variable SYAKAIHOKEN_KOJOGAKU "諸控除: 社会保険料控除額"
capture label variable SYOKIBO_KOJO "諸控除: 小規模企業共済等掛金控除額"
capture label variable IPPAN_SEIHO_KOJOGAKU "諸控除: 一般生命保険料控除額"
capture label variable KAIGO_IRYO_KOJO "諸控除: 介護医療保険料控除額"
capture label variable KOJIN_NENKIN_KOJO "諸控除: 個人年金保険料控除額"
capture label variable JISIN_KOJOGAKU "諸控除: 地震保険料控除額"
capture label variable HAIGU_TOKUBETU_KOJOGAKU "諸控除: 配偶者特別控除額"
capture label variable JUTAKU_KOJO "諸控除: 住宅借入金等特別控除額"
capture label variable NENZE_GAKU "年税額"
